OGRE: Ogre::LodInputProviderMesh Class Reference
Ogre::LodInputProviderMesh Class Reference
#include <OgreLodInputProviderMesh.h>
Public Member Functions
LodInputProviderMesh (MeshPtr mesh)
virtual void initData (LodData *data)
Called when the data should be filled with the input.
Protected Types
typedef vector< LodData::Vertex * >::type VertexLookupList
Protected Member Functions
void addIndexData (LodData *data, IndexData *indexData, bool useSharedVertexLookup, unsigned short submeshID, RenderOperation::OperationType renderOp)
template<typename IndexType >
void addIndexDataImpl (LodData *data, IndexType *iPos, const IndexType *iEnd, VertexLookupList &lookup, unsigned short submeshID, RenderOperation::OperationType renderOp)
void addTriangleToEdges (LodData *data, LodData::Triangle *triangle)
void addVertexData (LodData *data, VertexData *vertexData, bool useSharedVertexLookup)
void initialize (LodData *data)
bool isDuplicateTriangle (LodData::Triangle *triangle, LodData::Triangle *triangle2)
LodData::Triangle * isDuplicateTriangle (LodData::Triangle *triangle)
void printTriangle (LodData::Triangle *triangle, stringstream &str)
void tuneContainerSize (LodData *data)
Protected Attributes
MeshPtr mMesh
VertexLookupList mSharedVertexLookup
VertexLookupList mVertexLookup
Member Typedef Documentation
typedef vector<LodData::Vertex*>::type Ogre::LodInputProviderMesh::VertexLookupList protected
Constructor & Destructor Documentation
Ogre::LodInputProviderMesh::LodInputProviderMesh (MeshPtr mesh)
Member Function Documentation
void Ogre::LodInputProviderMesh::addIndexData (LodData * data, IndexData * indexData, bool useSharedVertexLookup, unsigned short submeshID, RenderOperation::OperationType renderOp) protected
template<typename IndexType > void Ogre::LodInputProviderMesh::addIndexDataImpl (LodData * data, IndexType * iPos, const IndexType * iEnd, VertexLookupList & lookup, unsigned short submeshID, RenderOperation::OperationType renderOp) inline protected
References Ogre::LodData::Triangle::computeNormal(), Ogre::LogManager::getSingleton(), Ogre::LodData::getVectorIDFromPointer(), Ogre::LodData::Triangle::isMalformed(), Ogre::LodData::Triangle::isRemoved, Ogre::LodData::mIndexBufferInfoList, Ogre::LodData::mTriangleList, OgreAssert, Ogre::RenderOperation::OT_TRIANGLE_FAN, Ogre::RenderOperation::OT_TRIANGLE_LIST, Ogre::RenderOperation::OT_TRIANGLE_STRIP, Ogre::LogManager::stream(), Ogre::LodData::Triangle::submeshID, Ogre::LodData::Triangle::vertex, and Ogre::LodData::Triangle::vertexID.
void Ogre::LodInputProvider::addTriangleToEdges (LodData * data, LodData::Triangle * triangle) protected inherited
void Ogre::LodInputProviderMesh::addVertexData (LodData * data, VertexData * vertexData, bool useSharedVertexLookup) protected
virtual void Ogre::LodInputProviderMesh::initData (LodData * data) virtual
Called when the data should be filled with the input.
Implements Ogre::LodInputProvider.
void Ogre::LodInputProviderMesh::initialize (LodData * data) protected
bool Ogre::LodInputProvider::isDuplicateTriangle (LodData::Triangle * triangle, LodData::Triangle * triangle2) protected inherited
LodData::Triangle* Ogre::LodInputProvider::isDuplicateTriangle (LodData::Triangle * triangle) protected inherited
void Ogre::LodInputProvider::printTriangle (LodData::Triangle * triangle, stringstream & str) protected inherited
void Ogre::LodInputProviderMesh::tuneContainerSize (LodData * data) protected
Member Data Documentation
MeshPtr Ogre::LodInputProviderMesh::mMesh protected
VertexLookupList Ogre::LodInputProviderMesh::mSharedVertexLookup protected
VertexLookupList Ogre::LodInputProviderMesh::mVertexLookup protected
The documentation for this class was generated from the following file:
OgreLodInputProviderMesh.h