OGRE: Ogre::AnyNumeric::numplaceholder Class Reference
Ogre::AnyNumeric::numplaceholder Class Reference abstract
#include <OgreAny.h>
Public Member Functions
~numplaceholder ()
virtual placeholder * add (placeholder *rhs)=0
virtual placeholder * clone () const =0
virtual placeholder * divide (placeholder *rhs)=0
virtual const std::type_info & getType () const =0
virtual placeholder * multiply (placeholder *rhs)=0
virtual placeholder * multiply (Real factor)=0
virtual placeholder * subtract (placeholder *rhs)=0
virtual void writeToStream (std::ostream &o)=0
Constructor & Destructor Documentation
Ogre::AnyNumeric::numplaceholder::~numplaceholder () inline
Member Function Documentation
virtual placeholder* Ogre::AnyNumeric::numplaceholder::add (placeholder * rhs) pure virtual
Implemented in Ogre::AnyNumeric::numholder< ValueType >.
virtual placeholder* Ogre::Any::placeholder::clone () const pure virtual inherited
Implemented in Ogre::AnyNumeric::numholder< ValueType >, and Ogre::Any::holder< ValueType >.
Referenced by Ogre::AnyNumeric::AnyNumeric(), and Ogre::Any::placeholder::~placeholder().
virtual placeholder* Ogre::AnyNumeric::numplaceholder::divide (placeholder * rhs) pure virtual
Implemented in Ogre::AnyNumeric::numholder< ValueType >.
virtual const std::type_info& Ogre::Any::placeholder::getType () const pure virtual inherited
Implemented in Ogre::AnyNumeric::numholder< ValueType >, and Ogre::Any::holder< ValueType >.
Referenced by Ogre::Any::get(), Ogre::Any::getType(), Ogre::Any::operator()(), and Ogre::Any::placeholder::~placeholder().
virtual placeholder* Ogre::AnyNumeric::numplaceholder::multiply (placeholder * rhs) pure virtual
Implemented in Ogre::AnyNumeric::numholder< ValueType >.
virtual placeholder* Ogre::AnyNumeric::numplaceholder::multiply (Real factor) pure virtual
Implemented in Ogre::AnyNumeric::numholder< ValueType >.
virtual placeholder* Ogre::AnyNumeric::numplaceholder::subtract (placeholder * rhs) pure virtual
Implemented in Ogre::AnyNumeric::numholder< ValueType >.
virtual void Ogre::Any::placeholder::writeToStream (std::ostream & o) pure virtual inherited
Implemented in Ogre::AnyNumeric::numholder< ValueType >, and Ogre::Any::holder< ValueType >.
Referenced by Ogre::Any::placeholder::~placeholder().
The documentation for this class was generated from the following file:
OgreAny.h