OGRE: Ogre::GLGpuNvparseProgram Class Reference
Ogre::GLGpuNvparseProgram Class Reference
#include <OgreGLGpuNvparseProgram.h>
Public Types
enum LoadingFlags {
LF_DEFAULT = 0, LF_INCLUDE_NON_RELOADABLE = 1, LF_ONLY_UNREFERENCED = 2, LF_ONLY_UNREFERENCED_INCLUDE_NON_RELOADABLE = 3,
LF_PRESERVE_STATE = 4
}
Enum that allow to choose subset of unloaded/reloaded resources and to adjust reloading behavior.
enum LoadingState {
LOADSTATE_UNLOADED, LOADSTATE_LOADING, LOADSTATE_LOADED, LOADSTATE_UNLOADING,
LOADSTATE_PREPARED, LOADSTATE_PREPARING
}
Enum identifying the loading state of the resource.
Public Member Functions
GLGpuNvparseProgram (ResourceManager *creator, const String &name, ResourceHandle handle, const String &group, bool isManual, ManualResourceLoader *loader)
virtual ~GLGpuNvparseProgram ()
virtual void _dirtyState ()
Manually mark the state of this resource as having been changed.
virtual void _fireLoadingComplete (bool wasBackgroundLoaded)
Firing of loading complete event.
virtual void _firePreparingComplete (bool wasBackgroundLoaded)
Firing of preparing complete event.
virtual void _fireUnloadingComplete (void)
Firing of unloading complete event.
virtual GpuProgram * _getBindingDelegate (void)
Returns the GpuProgram which should be bound to the pipeline.
virtual void _notifyOrigin (const String &origin)
Notify this resource of it's origin.
virtual void addListener (Listener *lis)
Register a listener on this resource.
void bindProgram (void)
Execute the binding functions for this program.
void bindProgramParameters (GpuProgramParametersSharedPtr params, uint16 mask)
Execute the param binding functions for this program.
virtual void bindProgramPassIterationParameters (GpuProgramParametersSharedPtr params)
Bind just the pass iteration parameters.
virtual size_t calculateSize (void) const
Calculate the size of a resource; this will only be called after 'load'.
virtual void changeGroupOwnership (const String &newGroup)
Change the resource group ownership of a Resource.
virtual void copyParametersTo (StringInterface *dest) const
Method for copying this object's parameters to another object.
virtual GpuProgramParametersSharedPtr createParameters (void)
Creates a new parameters object compatible with this program definition.
virtual void escalateLoading ()
Escalates the loading of a background loaded resource.
virtual GLuint getAttributeIndex (VertexElementSemantic semantic, uint index)
Get the attribute index for a given semantic.
virtual Vector3 getComputeGroupDimensions (void) const
Returns the number of process groups dispatched by this compute program.
virtual const GpuNamedConstants & getConstantDefinitions () const
Get the full list of named constants.
virtual ResourceManager * getCreator (void)
Gets the manager which created this resource.
virtual GpuProgramParametersSharedPtr getDefaultParameters (void)
Get a reference to the default parameters which are to be used for all uses of this program.
virtual const String & getGroup (void) const
Gets the group which this resource is a member of.
virtual ResourceHandle getHandle (void) const
virtual const String & getLanguage (void) const
Returns a string that specifies the language of the gpu programs as specified in a material script.
virtual LoadingState getLoadingState () const
Returns the current loading state.
virtual const String & getManualNamedConstantsFile () const
Gets the name of a file from which to load named parameters mapping for a program which would not be able to derive named parameters itself.
virtual const String & getName (void) const
Gets resource name.
virtual ushort getNumberOfPosesIncluded (void) const
Returns the number of simultaneous poses the vertex program can blend, for use in pose animation.
virtual const String & getOrigin (void) const
Get the origin of this resource, e.g.
ParamDictionary * getParamDictionary (void)
Retrieves the parameter dictionary for this class.
const ParamDictionary * getParamDictionary (void) const
virtual String getParameter (const String &name) const
Generic parameter retrieval method.
const ParameterList & getParameters (void) const
Retrieves a list of parameters valid for this object.
virtual bool getPassFogStates (void) const
Returns whether a fragment program wants fog state to be passed through fixed pipeline low level API rendering calls (default true, subclasses can override)
virtual bool getPassSurfaceAndLightStates (void) const
Returns whether a vertex program wants light and material states to be passed through fixed pipeline low level API rendering calls (default false, subclasses can override)
virtual bool getPassTransformStates (void) const
Returns whether a vertex program wants transform state to be passed through fixed pipeline low level API rendering calls.
GLuint getProgramID (void) const
Get the assigned GL program id.
virtual size_t getSize (void) const
Retrieves info about the size of the resource.
virtual const String & getSource (void) const
Gets the assembler source for this program.
virtual const String & getSourceFile (void) const
Gets the name of the file used as source for this program.
virtual size_t getStateCount () const
Returns the number of times this resource has changed state, which generally means the number of times it has been loaded.
virtual const String & getSyntaxCode (void) const
Gets the syntax code for this program e.g.
virtual GpuProgramType getType (void) const
Get the program type.
virtual bool hasCompileError (void) const
Did this program encounter a compile error when loading?
virtual bool hasDefaultParameters (void) const
Returns true if default parameters have been set up.
virtual bool isAdjacencyInfoRequired (void) const
Returns whether this geometry program requires adjacency information from the input primitives.
virtual bool isAttributeValid (VertexElementSemantic semantic, uint index)
Test whether attribute index for a given semantic is valid.
virtual bool isBackgroundLoaded (void) const
Returns whether this Resource has been earmarked for background loading.
virtual bool isLoaded (void) const
Returns true if the Resource has been loaded, false otherwise.
virtual bool isLoading () const
Returns whether the resource is currently in the process of background loading.
virtual bool isManuallyLoaded (void) const
Is this resource manually loaded?
virtual bool isMorphAnimationIncluded (void) const
Returns whether a vertex program includes the required instructions to perform morph animation.
virtual bool isPoseAnimationIncluded (void) const
Returns whether a vertex program includes the required instructions to perform pose animation.
virtual bool isPrepared (void) const
Returns true if the Resource has been prepared, false otherwise.
virtual bool isReloadable (void) const
Returns true if the Resource is reloadable, false otherwise.
virtual bool isSkeletalAnimationIncluded (void) const
Returns whether a vertex program includes the required instructions to perform skeletal animation.
virtual bool isSupported (void) const
Returns whether this program can be supported on the current renderer and hardware.
virtual bool isVertexTextureFetchRequired (void) const
Returns whether this vertex program requires support for vertex texture fetch from the hardware.
virtual void load (bool backgroundThread=false)
Loads the resource, if it is not already.
virtual void prepare (bool backgroundThread=false)
Prepares the resource for load, if it is not already.
virtual void reload (LoadingFlags flags=LF_DEFAULT)
Reloads the resource, if it is already loaded.
virtual void removeListener (Listener *lis)
Remove a listener on this resource.
virtual void resetCompileError (void)
Reset a compile error if it occurred, allowing the load to be retried.
virtual void setAdjacencyInfoRequired (bool r)
Sets whether this geometry program requires adjacency information from the input primitives.
virtual void setBackgroundLoaded (bool bl)
Tells the resource whether it is background loaded or not.
virtual void setComputeGroupDimensions (Vector3 dimensions)
Sets the number of process groups dispatched by this compute program.
virtual void setManuallyLoaded (bool isManual)
Set "Is this resource manually loaded?".
virtual void setManualNamedConstants (const GpuNamedConstants &namedConstants)
Allows you to manually provide a set of named parameter mappings to a program which would not be able to derive named parameters itself.
virtual void setManualNamedConstantsFile (const String &paramDefFile)
Specifies the name of a file from which to load named parameters mapping for a program which would not be able to derive named parameters itself.
virtual void setMorphAnimationIncluded (bool included)
Sets whether a vertex program includes the required instructions to perform morph animation.
virtual bool setParameter (const String &name, const String &value)
Generic parameter setting method.
virtual void setParameterList (const NameValuePairList &paramList)
Generic multiple parameter setting method.
virtual void setPoseAnimationIncluded (ushort poseCount)
Sets whether a vertex program includes the required instructions to perform pose animation.
virtual void setSkeletalAnimationIncluded (bool included)
Sets whether a vertex program includes the required instructions to perform skeletal animation.
virtual void setSource (const String &source)
Sets the source assembly for this program from an in-memory string.
virtual void setSourceFile (const String &filename)
Sets the filename of the source assembly for this program.
virtual void setSyntaxCode (const String &syntax)
Sets the syntax code for this program e.g.
virtual void setToLoaded (void)
Change the Resource loading state to loaded.
virtual void setType (GpuProgramType t)
Set the program type (only valid before load)
virtual void setVertexTextureFetchRequired (bool r)
Sets whether this vertex program requires support for vertex texture fetch from the hardware.
virtual void touch (void)
'Touches' the resource to indicate it has been used.
void unbindProgram (void)
Execute the unbinding functions for this program.
virtual void unload (void)
Unloads the resource; this is not permanent, the resource can be reloaded later if required.
Static Public Member Functions
static void cleanupDictionary ()
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
static GLuint getFixedAttributeIndex (VertexElementSemantic semantic, uint index)
Get the fixed attribute bindings normally used by GL for a semantic.
static const String getProgramTypeName (GpuProgramType programType)
Public Attributes
OGRE_AUTO_MUTEX
Protected Types
typedef set< Listener * >::type ListenerList
Protected Member Functions
void createLogicalParameterMappingStructures (bool recreateIfExists=true) const
Create the internal params logical mapping structures.
void createNamedParameterMappingStructures (bool recreateIfExists=true) const
Create the internal params named mapping structures.
bool createParamDictionary (const String &className)
Internal method for creating a parameter dictionary for the class, if it does not already exist.
void createParameterMappingStructures (bool recreateIfExists=true) const
Create the internal params logical & named mapping structures.
bool isRequiredCapabilitiesSupported (void) const
Internal method returns whether required capabilities for this program is supported.
void loadFromSource (void)
Virtual method which must be implemented by subclasses, load from mSource.
void loadImpl (void)
Internal implementation of the meat of the 'load' action, only called if this resource is not being loaded from a ManualResourceLoader.
OGRE_MUTEX (mListenerListMutex)
virtual void postLoadImpl (void)
Internal hook to perform actions after the load process, but before the resource has been marked as fully loaded.
virtual void postUnloadImpl (void)
Internal hook to perform actions after the unload process, but before the resource has been marked as fully unloaded.
virtual void preLoadImpl (void)
Internal hook to perform actions before the load process, but after the resource has been marked as 'loading'.
virtual void prepareImpl (void)
Internal implementation of the meat of the 'prepare' action.
virtual void preUnloadImpl (void)
Internal hook to perform actions before the unload process.
void setupBaseParamDictionary (void)
Internal method for setting up the basic parameter definitions for a subclass.
void unloadImpl (void)
Unloads the resource; this is not permanent, the resource can be reloaded later if required.
virtual void unprepareImpl (void)
Internal function for undoing the 'prepare' action.
Protected Attributes
GpuLogicalBufferStructPtr mBoolLogicalToPhysical
Record of logical to physical buffer maps.
bool mCompileError
Did we encounter a compilation error?
Vector3 mComputeGroupDimensions
The number of process groups dispatched by this (compute) program.
GpuNamedConstantsPtr mConstantDefs
Parameter name -> ConstantDefinition map, shared instance used by all parameter objects.
ResourceManager * mCreator
Creator.
GpuProgramParametersSharedPtr mDefaultParams
The default parameters for use with this object.
GpuLogicalBufferStructPtr mDoubleLogicalToPhysical
Record of logical to physical buffer maps.
String mFilename
The name of the file to load source from (may be blank)
GpuLogicalBufferStructPtr mFloatLogicalToPhysical
Record of logical to physical buffer maps.
String mGroup
The name of the resource group.
ResourceHandle mHandle
Numeric handle for more efficient look up than name.
GpuLogicalBufferStructPtr mIntLogicalToPhysical
Record of logical to physical buffer maps.
volatile bool mIsBackgroundLoaded
Is this resource going to be background loaded? Only applicable for multithreaded.
bool mIsManual
Is this file manually loaded?
ListenerList mListenerList
bool mLoadedManualNamedConstants
ManualResourceLoader * mLoader
Optional manual loader; if provided, data is loaded from here instead of a file.
bool mLoadFromFile
Whether we need to load source from file or not.
AtomicScalar< LoadingState > mLoadingState
Is the resource currently loaded?
String mManualNamedConstantsFile
File from which to load named constants manually.
bool mMorphAnimation
Does this (vertex) program include morph animation?
String mName
Unique name of the resource.
bool mNeedsAdjacencyInfo
Does this (geometry) program require adjacency information?
String mOrigin
Origin of this resource (e.g. script name) - optional.
ushort mPoseAnimation
Does this (vertex) program include pose animation (count of number of poses supported)
GLenum mProgramType
size_t mSize
The size of the resource in bytes.
bool mSkeletalAnimation
Does this (vertex) program include skeletal animation?
String mSource
The assembler source of the program (may be blank until file loaded)
size_t mStateCount
State count, the number of times this resource has changed state.
String mSyntaxCode
Syntax code e.g. arbvp1, vs_2_0 etc.
GpuProgramType mType
The type of the program.
GpuLogicalBufferStructPtr mUIntLogicalToPhysical
Record of logical to physical buffer maps.
bool mVertexTextureFetch
Does this (vertex) program require support for vertex texture fetch?
Static Protected Attributes
static CmdAdjacency msAdjacencyCmd
static CmdComputeGroupDims msComputeGroupDimsCmd
static CmdManualNamedConstsFile msManNamedConstsFileCmd
static CmdMorph msMorphCmd
static CmdPose msPoseCmd
static CmdSkeletal msSkeletalCmd
static CmdSyntax msSyntaxCmd
static CmdType msTypeCmd
static CmdVTF msVTFCmd
Member Typedef Documentation
typedef set<Listener*>::type Ogre::Resource::ListenerList protected inherited
Member Enumeration Documentation
enum Ogre::Resource::LoadingFlags inherited
Enum that allow to choose subset of unloaded/reloaded resources and to adjust reloading behavior.
Enumerator
LF_DEFAULT
Only reloadable resources are processed, reload restores initial state.
LF_INCLUDE_NON_RELOADABLE
Process non-reloadable resources too.
LF_ONLY_UNREFERENCED
Process only resources which are not referenced by any other object. Usefull to reduce resource consumption.
LF_ONLY_UNREFERENCED_INCLUDE_NON_RELOADABLE
Combination of LF_ONLY_UNREFERENCED and LF_INCLUDE_NON_RELOADABLE.
LF_PRESERVE_STATE
Preserve some states during reloading, for example stencil shadows prepareness for Meshes.
enum Ogre::Resource::LoadingState inherited
Enum identifying the loading state of the resource.
Enumerator
LOADSTATE_UNLOADED
Not loaded.
LOADSTATE_LOADING
Loading is in progress.
LOADSTATE_LOADED
Fully loaded.
LOADSTATE_UNLOADING
Currently unloading.
LOADSTATE_PREPARED
Fully prepared.
LOADSTATE_PREPARING
Preparing is in progress.
Constructor & Destructor Documentation
Ogre::GLGpuNvparseProgram::GLGpuNvparseProgram (ResourceManager * creator, const String & name, ResourceHandle handle, const String & group, bool isManual, ManualResourceLoader * loader)
virtual Ogre::GLGpuNvparseProgram::~GLGpuNvparseProgram () virtual
Member Function Documentation
virtual void Ogre::Resource::_dirtyState () virtual inherited
Manually mark the state of this resource as having been changed.
Remarks
You only need to call this from outside if you explicitly want derived objects to think this object has changed.
See also
getStateCount.
virtual void Ogre::Resource::_fireLoadingComplete (bool wasBackgroundLoaded) virtual inherited
Firing of loading complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
Parameters
wasBackgroundLoaded Whether this was a background loaded event
virtual void Ogre::Resource::_firePreparingComplete (bool wasBackgroundLoaded) virtual inherited
Firing of preparing complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
Parameters
wasBackgroundLoaded Whether this was a background loaded event
virtual void Ogre::Resource::_fireUnloadingComplete (void) virtual inherited
Firing of unloading complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
virtual GpuProgram* Ogre::GpuProgram::_getBindingDelegate (void) inline virtual inherited
Returns the GpuProgram which should be bound to the pipeline.
Remarks
This method is simply to allow some subclasses of GpuProgram to delegate the program which is bound to the pipeline to a delegate, if required.
Reimplemented in Ogre::GLSLShader, Ogre::UnifiedHighLevelGpuProgram, and Ogre::HighLevelGpuProgram.
virtual void Ogre::Resource::_notifyOrigin (const String & origin) inline virtual inherited
Notify this resource of it's origin.
virtual void Ogre::Resource::addListener (Listener * lis) virtual inherited
Register a listener on this resource.
See also
Resource::Listener
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
void Ogre::GLGpuNvparseProgram::bindProgram (void) virtual
Execute the binding functions for this program.
Reimplemented from Ogre::GLGpuProgram.
void Ogre::GLGpuNvparseProgram::bindProgramParameters (GpuProgramParametersSharedPtr params, uint16 mask) virtual
Execute the param binding functions for this program.
Reimplemented from Ogre::GLGpuProgram.
virtual void Ogre::GLGpuProgram::bindProgramPassIterationParameters (GpuProgramParametersSharedPtr params) inline virtual inherited
Bind just the pass iteration parameters.
Reimplemented in Ogre::GLArbGpuProgram, and Ogre::GLSL::GLSLGpuProgram.
virtual size_t Ogre::GLGpuProgram::calculateSize (void) const virtual inherited
Calculate the size of a resource; this will only be called after 'load'.
Reimplemented from Ogre::GpuProgram.
virtual void Ogre::Resource::changeGroupOwnership (const String & newGroup) virtual inherited
Change the resource group ownership of a Resource.
Remarks
This method is generally reserved for internal use, although if you really know what you're doing you can use it to move this resource from one group to another.
Parameters
newGroup Name of the new group
static void Ogre::StringInterface::cleanupDictionary () static inherited
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
MaterialManager) initializes.
virtual void Ogre::StringInterface::copyParametersTo (StringInterface * dest) const inline virtual inherited
Method for copying this object's parameters to another object.
Remarks
This method takes the values of all the object's parameters and tries to set the same values on the destination object. This provides a completely type independent way to copy parameters to other objects. Note that because of the String manipulation involved, this should not be regarded as an efficient process and should be saved for times outside of the rendering loop.
Any unrecognised parameters will be ignored as with setParameter method.
Parameters
dest Pointer to object to have it's parameters set the same as this object.
References Ogre::ParamDictionary::mParamDefs, and Ogre::StringInterface::setParameter().
void Ogre::GpuProgram::createLogicalParameterMappingStructures (bool recreateIfExists = true) const protected inherited
Create the internal params logical mapping structures.
void Ogre::GpuProgram::createNamedParameterMappingStructures (bool recreateIfExists = true) const protected inherited
Create the internal params named mapping structures.
bool Ogre::StringInterface::createParamDictionary (const String & className) inline protected inherited
Internal method for creating a parameter dictionary for the class, if it does not already exist.
Remarks
This method will check to see if a parameter dictionary exist for this class yet, and if not will create one. NB you must supply the name of the class (RTTI is not used or performance).
Parameters
className the name of the class using the dictionary
Returns
true if a new dictionary was created, false if it was already there
References OGRE_LOCK_MUTEX.
void Ogre::GpuProgram::createParameterMappingStructures (bool recreateIfExists = true) const protected inherited
Create the internal params logical & named mapping structures.
virtual GpuProgramParametersSharedPtr Ogre::GpuProgram::createParameters (void) virtual inherited
Creates a new parameters object compatible with this program definition.
Remarks
It is recommended that you use this method of creating parameters objects rather than going direct to GpuProgramManager, because this method will populate any implementation-specific extras (like named parameters) where they are appropriate.
Reimplemented in Ogre::D3D11HLSLProgram, Ogre::D3D9HLSLProgram, Ogre::GLSLShader, Ogre::UnifiedHighLevelGpuProgram, Ogre::HighLevelGpuProgram, and Ogre::D3D9GpuProgram.
virtual void Ogre::Resource::escalateLoading () virtual inherited
Escalates the loading of a background loaded resource.
Remarks
If a resource is set to load in the background, but something needs it before it's been loaded, there could be a problem. If the user of this resource really can't wait, they can escalate the loading which basically pulls the loading into the current thread immediately. If the resource is already being loaded but just hasn't quite finished then this method will simply wait until the background load is complete.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual GLuint Ogre::GLGpuProgram::getAttributeIndex (VertexElementSemantic semantic, uint index) virtual inherited
Get the attribute index for a given semantic.
Remarks
This can be used to identify the attribute index to bind non-builtin attributes like tangent and binormal.
Reimplemented in Ogre::GLSL::GLSLGpuProgram.
virtual Vector3 Ogre::GpuProgram::getComputeGroupDimensions (void) const inline virtual inherited
Returns the number of process groups dispatched by this compute program.
virtual const GpuNamedConstants& Ogre::GpuProgram::getConstantDefinitions () const inline virtual inherited
Get the full list of named constants.
Note
Only available if this parameters object has named parameters, which means either a high-level program which loads them, or a low-level program which has them specified manually.
Reimplemented in Ogre::HighLevelGpuProgram.
References Ogre::SharedPtr< T >::get().
virtual ResourceManager* Ogre::Resource::getCreator (void) inline virtual inherited
Gets the manager which created this resource.
virtual GpuProgramParametersSharedPtr Ogre::GpuProgram::getDefaultParameters (void) virtual inherited
Get a reference to the default parameters which are to be used for all uses of this program.
Remarks
A program can be set up with a list of default parameters, which can save time when using a program many times in a material with roughly the same settings. By retrieving the default parameters and populating it with the most used options, any new parameter objects created from this program afterwards will automatically include the default parameters; thus users of the program need only change the parameters which are unique to their own usage of the program.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
static GLuint Ogre::GLGpuProgram::getFixedAttributeIndex (VertexElementSemantic semantic, uint index) static inherited
Get the fixed attribute bindings normally used by GL for a semantic.
virtual const String& Ogre::Resource::getGroup (void) const inline virtual inherited
Gets the group which this resource is a member of.
Reimplemented in Ogre::SkeletonInstance.
virtual ResourceHandle Ogre::Resource::getHandle (void) const inline virtual inherited
Reimplemented in Ogre::SkeletonInstance.
virtual const String& Ogre::GpuProgram::getLanguage (void) const virtual inherited
Returns a string that specifies the language of the gpu programs as specified in a material script.
ie: asm, cg, hlsl, glsl
Reimplemented in Ogre::D3D11HLSLProgram, Ogre::D3D9HLSLProgram, Ogre::GLSLShader, Ogre::UnifiedHighLevelGpuProgram, and Ogre::GLSL::GLSLProgram.
virtual LoadingState Ogre::Resource::getLoadingState () const inline virtual inherited
Returns the current loading state.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::get().
virtual const String& Ogre::GpuProgram::getManualNamedConstantsFile () const inline virtual inherited
Gets the name of a file from which to load named parameters mapping for a program which would not be able to derive named parameters itself.
virtual const String& Ogre::Resource::getName (void) const inline virtual inherited
Gets resource name.
Reimplemented in Ogre::SkeletonInstance.
Referenced by Ogre::GpuProgramUsage::getProgramName(), and OgreBites::TrayManager::resourceLoadStarted().
virtual ushort Ogre::GpuProgram::getNumberOfPosesIncluded (void) const inline virtual inherited
Returns the number of simultaneous poses the vertex program can blend, for use in pose animation.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual const String& Ogre::Resource::getOrigin (void) const inline virtual inherited
Get the origin of this resource, e.g.
a script file name.
Remarks
This property will only contain something if the creator of this resource chose to populate it. Script loaders are advised to populate it.
ParamDictionary* Ogre::StringInterface::getParamDictionary (void) inline inherited
Retrieves the parameter dictionary for this class.
Remarks
Only valid to call this after createParamDictionary.
Returns
Pointer to ParamDictionary shared by all instances of this class which you can add parameters to, retrieve parameters etc.
const ParamDictionary* Ogre::StringInterface::getParamDictionary (void) const inline inherited
virtual String Ogre::StringInterface::getParameter (const String & name) const inline virtual inherited
Generic parameter retrieval method.
Remarks
Call this method with the name of a parameter to retrieve a string-format value of the parameter in question. If in doubt, check the parameter definition in the list returned from getParameters for the type of this parameter. If you like you can use StringConverter to convert this string back into a native type.
Parameters
name The name of the parameter to get
Returns
String value of parameter, blank if not found
References Ogre::ParamCommand::doGet(), and Ogre::ParamDictionary::getParamCommand().
const ParameterList& Ogre::StringInterface::getParameters (void) const inherited
Retrieves a list of parameters valid for this object.
Returns
A reference to a static list of ParameterDef objects.
virtual bool Ogre::GpuProgram::getPassFogStates (void) const inline virtual inherited
Returns whether a fragment program wants fog state to be passed through fixed pipeline low level API rendering calls (default true, subclasses can override)
Remarks
On DirectX, shader model 2 and earlier continues to have fixed-function fog applied to it, so fog state is still passed (you should disable fog on the pass if you want to perform fog in the shader). In OpenGL it is also common to be able to access the fixed-function fog state inside the shader.
Reimplemented in Ogre::GLSLShader, and Ogre::UnifiedHighLevelGpuProgram.
virtual bool Ogre::GpuProgram::getPassSurfaceAndLightStates (void) const inline virtual inherited
Returns whether a vertex program wants light and material states to be passed through fixed pipeline low level API rendering calls (default false, subclasses can override)
Remarks
Most vertex programs do not need this material information, however GLSL shaders can refer to this material and lighting state so enable this option
Reimplemented in Ogre::GLSLShader, Ogre::UnifiedHighLevelGpuProgram, and Ogre::GLSL::GLSLProgram.
virtual bool Ogre::GpuProgram::getPassTransformStates (void) const inline virtual inherited
Returns whether a vertex program wants transform state to be passed through fixed pipeline low level API rendering calls.
Remarks
Most vertex programs do not need fixed-function transform information, however GLSL shaders can refer to this state so enable this option
Reimplemented in Ogre::GLSLShader, Ogre::UnifiedHighLevelGpuProgram, and Ogre::GLSL::GLSLProgram.
GLuint Ogre::GLGpuNvparseProgram::getProgramID (void) const inline
Get the assigned GL program id.
static const String Ogre::GpuProgram::getProgramTypeName (GpuProgramType programType) static inherited
virtual size_t Ogre::Resource::getSize (void) const inline virtual inherited
Retrieves info about the size of the resource.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual const String& Ogre::GpuProgram::getSource (void) const inline virtual inherited
Gets the assembler source for this program.
virtual const String& Ogre::GpuProgram::getSourceFile (void) const inline virtual inherited
Gets the name of the file used as source for this program.
virtual size_t Ogre::Resource::getStateCount () const inline virtual inherited
Returns the number of times this resource has changed state, which generally means the number of times it has been loaded.
Objects that build derived data based on the resource can check this value against a copy they kept last time they built this derived data, in order to know whether it needs rebuilding. This is a nice way of monitoring changes without having a tightly-bound callback.
virtual const String& Ogre::GpuProgram::getSyntaxCode (void) const inline virtual inherited
Gets the syntax code for this program e.g.
arbvp1, fp20, vs_1_1 etc
virtual GpuProgramType Ogre::GpuProgram::getType (void) const inline virtual inherited
Get the program type.
virtual bool Ogre::GpuProgram::hasCompileError (void) const inline virtual inherited
Did this program encounter a compile error when loading?
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual bool Ogre::GpuProgram::hasDefaultParameters (void) const inline virtual inherited
Returns true if default parameters have been set up.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::SharedPtr< T >::isNull().
virtual bool Ogre::GpuProgram::isAdjacencyInfoRequired (void) const inline virtual inherited
Returns whether this geometry program requires adjacency information from the input primitives.
virtual bool Ogre::GLGpuProgram::isAttributeValid (VertexElementSemantic semantic, uint index) virtual inherited
Test whether attribute index for a given semantic is valid.
Reimplemented in Ogre::GLSL::GLSLGpuProgram.
virtual bool Ogre::Resource::isBackgroundLoaded (void) const inline virtual inherited
Returns whether this Resource has been earmarked for background loading.
Remarks
This option only makes sense when you have built Ogre with thread support (OGRE_THREAD_SUPPORT). If a resource has been marked for background loading, then it won't load on demand like normal when load() is called. Instead, it will ignore request to load() except if the caller indicates it is the background loader. Any other users of this resource should check isLoaded(), and if that returns false, don't use the resource and come back later.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual bool Ogre::Resource::isLoaded (void) const inline virtual inherited
Returns true if the Resource has been loaded, false otherwise.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::get().
virtual bool Ogre::Resource::isLoading () const inline virtual inherited
Returns whether the resource is currently in the process of background loading.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::get().
virtual bool Ogre::Resource::isManuallyLoaded (void) const inline virtual inherited
Is this resource manually loaded?
virtual bool Ogre::GpuProgram::isMorphAnimationIncluded (void) const inline virtual inherited
Returns whether a vertex program includes the required instructions to perform morph animation.
Remarks
If this returns true, OGRE will not blend the geometry according to morph animation, it will expect the vertex program to do it.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual bool Ogre::GpuProgram::isPoseAnimationIncluded (void) const inline virtual inherited
Returns whether a vertex program includes the required instructions to perform pose animation.
Remarks
If this returns true, OGRE will not blend the geometry according to pose animation, it will expect the vertex program to do it.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual bool Ogre::Resource::isPrepared (void) const inline virtual inherited
Returns true if the Resource has been prepared, false otherwise.
References Ogre::AtomicScalar< T >::get().
virtual bool Ogre::Resource::isReloadable (void) const inline virtual inherited
Returns true if the Resource is reloadable, false otherwise.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
bool Ogre::GpuProgram::isRequiredCapabilitiesSupported (void) const protected inherited
Internal method returns whether required capabilities for this program is supported.
virtual bool Ogre::GpuProgram::isSkeletalAnimationIncluded (void) const inline virtual inherited
Returns whether a vertex program includes the required instructions to perform skeletal animation.
Remarks
If this returns true, OGRE will not blend the geometry according to skeletal animation, it will expect the vertex program to do it.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual bool Ogre::GpuProgram::isSupported (void) const virtual inherited
Returns whether this program can be supported on the current renderer and hardware.
Reimplemented in Ogre::D3D11HLSLProgram, Ogre::D3D9HLSLProgram, and Ogre::UnifiedHighLevelGpuProgram.
virtual bool Ogre::GpuProgram::isVertexTextureFetchRequired (void) const inline virtual inherited
Returns whether this vertex program requires support for vertex texture fetch from the hardware.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::Resource::load (bool backgroundThread = false) virtual inherited
Loads the resource, if it is not already.
Remarks
If the resource is loaded from a file, loading is automatic. If not, if for example this resource gained it's data from procedural calls rather than loading from a file, then this resource will not reload on it's own.
Parameters
backgroundThread Indicates whether the caller of this method is the background resource loading thread.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
void Ogre::GLGpuNvparseProgram::loadFromSource (void) protected virtual
Virtual method which must be implemented by subclasses, load from mSource.
Implements Ogre::GpuProgram.
void Ogre::GpuProgram::loadImpl (void) protected virtual inherited
Internal implementation of the meat of the 'load' action, only called if this resource is not being loaded from a ManualResourceLoader.
Implements Ogre::Resource.
Reimplemented in Ogre::GLSLESGpuProgram, Ogre::HighLevelGpuProgram, Ogre::GLSL::GLSLGpuProgram, and Ogre::D3D9GpuProgram.
Ogre::Resource::OGRE_MUTEX (mListenerListMutex) protected inherited
virtual void Ogre::Resource::postLoadImpl (void) inline protected virtual inherited
Internal hook to perform actions after the load process, but before the resource has been marked as fully loaded.
Note
Mutex will have already been acquired by the loading thread. Also, this call will occur even when using a ManualResourceLoader (when loadImpl is not actually called)
Reimplemented in Ogre::Mesh, Ogre::D3D11Texture, and Ogre::D3D9Texture.
virtual void Ogre::Resource::postUnloadImpl (void) inline protected virtual inherited
Internal hook to perform actions after the unload process, but before the resource has been marked as fully unloaded.
Note
Mutex will have already been acquired by the unloading thread.
virtual void Ogre::Resource::preLoadImpl (void) inline protected virtual inherited
Internal hook to perform actions before the load process, but after the resource has been marked as 'loading'.
Note
Mutex will have already been acquired by the loading thread. Also, this call will occur even when using a ManualResourceLoader (when loadImpl is not actually called)
virtual void Ogre::Resource::prepare (bool backgroundThread = false) virtual inherited
Prepares the resource for load, if it is not already.
One can call prepare() before load(), but this is not required as load() will call prepare() itself, if needed. When OGRE_THREAD_SUPPORT==1 both load() and prepare() are thread-safe. When OGRE_THREAD_SUPPORT==2 however, only prepare() is thread-safe. The reason for this function is to allow a background thread to do some of the loading work, without requiring the whole render system to be thread-safe. The background thread would call prepare() while the main render loop would later call load(). So long as prepare() remains thread-safe, subclasses can arbitrarily split the work of loading a resource between load() and prepare(). It is best to try and do as much work in prepare(), however, since this will leave less work for the main render thread to do and thus increase FPS.
Parameters
backgroundThread Whether this is occurring in a background thread
virtual void Ogre::Resource::prepareImpl (void) inline protected virtual inherited
Internal implementation of the meat of the 'prepare' action.
Reimplemented in Ogre::Mesh, Ogre::D3D11Texture, Ogre::D3D9Texture, Ogre::Material, Ogre::PatchMesh, Ogre::GL3PlusTexture, and Ogre::GLTexture.
virtual void Ogre::Resource::preUnloadImpl (void) inline protected virtual inherited
Internal hook to perform actions before the unload process.
Note
Mutex will have already been acquired by the unloading thread.
virtual void Ogre::Resource::reload (LoadingFlags flags = LF_DEFAULT) virtual inherited
Reloads the resource, if it is already loaded.
Remarks
Calls unload() and then load() again, if the resource is already loaded. If it is not loaded already, then nothing happens.
Reimplemented in Ogre::Mesh, and Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::Resource::removeListener (Listener * lis) virtual inherited
Remove a listener on this resource.
See also
Resource::Listener
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::GpuProgram::resetCompileError (void) inline virtual inherited
Reset a compile error if it occurred, allowing the load to be retried.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::GpuProgram::setAdjacencyInfoRequired (bool r) inline virtual inherited
Sets whether this geometry program requires adjacency information from the input primitives.
virtual void Ogre::Resource::setBackgroundLoaded (bool bl) inline virtual inherited
Tells the resource whether it is background loaded or not.
See also
Resource::isBackgroundLoaded. Note that calling this only defers the normal on-demand loading behaviour of a resource, it does not actually set up a thread to make sure the resource gets loaded in the background. You should use ResourceBackgroundLoadingQueue to manage the actual loading (which will call this method itself).
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::GpuProgram::setComputeGroupDimensions (Vector3 dimensions) inline virtual inherited
Sets the number of process groups dispatched by this compute program.
virtual void Ogre::Resource::setManuallyLoaded (bool isManual) inline virtual inherited
Set "Is this resource manually loaded?".
virtual void Ogre::GpuProgram::setManualNamedConstants (const GpuNamedConstants & namedConstants) virtual inherited
Allows you to manually provide a set of named parameter mappings to a program which would not be able to derive named parameters itself.
Remarks
You may wish to use this if you have assembler programs that were compiled from a high-level source, and want the convenience of still being able to use the named parameters from the original high-level source.
See also
setManualNamedConstantsFile
virtual void Ogre::GpuProgram::setManualNamedConstantsFile (const String & paramDefFile) virtual inherited
Specifies the name of a file from which to load named parameters mapping for a program which would not be able to derive named parameters itself.
Remarks
You may wish to use this if you have assembler programs that were compiled from a high-level source, and want the convenience of still being able to use the named parameters from the original high-level source. This method will make a low-level program search in the resource group of the program for the named file from which to load parameter names from. The file must be in the format produced by GpuNamedConstants::save.
virtual void Ogre::GpuProgram::setMorphAnimationIncluded (bool included) inline virtual inherited
Sets whether a vertex program includes the required instructions to perform morph animation.
Remarks
If this is set to true, OGRE will not blend the geometry according to morph animation, it will expect the vertex program to do it.
virtual bool Ogre::StringInterface::setParameter (const String & name, const String & value) virtual inherited
Generic parameter setting method.
Remarks
Call this method with the name of a parameter and a string version of the value to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
name The name of the parameter to set
value String value. Must be in the right format for the type specified in the parameter definition. See the StringConverter class for more information.
Returns
true if set was successful, false otherwise (NB no exceptions thrown - tolerant method)
Referenced by Ogre::StringInterface::copyParametersTo().
virtual void Ogre::StringInterface::setParameterList (const NameValuePairList & paramList) virtual inherited
Generic multiple parameter setting method.
Remarks
Call this method with a list of name / value pairs to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
paramList Name/value pair list
virtual void Ogre::GpuProgram::setPoseAnimationIncluded (ushort poseCount) inline virtual inherited
Sets whether a vertex program includes the required instructions to perform pose animation.
Remarks
If this is set to true, OGRE will not blend the geometry according to pose animation, it will expect the vertex program to do it.
Parameters
poseCount The number of simultaneous poses the program can blend
virtual void Ogre::GpuProgram::setSkeletalAnimationIncluded (bool included) inline virtual inherited
Sets whether a vertex program includes the required instructions to perform skeletal animation.
Remarks
If this is set to true, OGRE will not blend the geometry according to skeletal animation, it will expect the vertex program to do it.
virtual void Ogre::GpuProgram::setSource (const String & source) virtual inherited
Sets the source assembly for this program from an in-memory string.
Remarks
Setting this will have no effect until you (re)load the program.
virtual void Ogre::GpuProgram::setSourceFile (const String & filename) virtual inherited
Sets the filename of the source assembly for this program.
Remarks
Setting this will have no effect until you (re)load the program.
virtual void Ogre::GpuProgram::setSyntaxCode (const String & syntax) virtual inherited
Sets the syntax code for this program e.g.
arbvp1, fp20, vs_1_1 etc
virtual void Ogre::Resource::setToLoaded (void) inline virtual inherited
Change the Resource loading state to loaded.
References Ogre::AtomicScalar< T >::set().
virtual void Ogre::GpuProgram::setType (GpuProgramType t) virtual inherited
Set the program type (only valid before load)
Reimplemented in Ogre::GLArbGpuProgram.
void Ogre::GpuProgram::setupBaseParamDictionary (void) protected inherited
Internal method for setting up the basic parameter definitions for a subclass.
Remarks
Because StringInterface holds a dictionary of parameters per class, subclasses need to call this to ask the base class to add it's parameters to their dictionary as well. Can't do this in the constructor because that runs in a non-virtual context.
The subclass must have called it's own createParamDictionary before calling this method.
virtual void Ogre::GpuProgram::setVertexTextureFetchRequired (bool r) inline virtual inherited
Sets whether this vertex program requires support for vertex texture fetch from the hardware.
virtual void Ogre::Resource::touch (void) virtual inherited
'Touches' the resource to indicate it has been used.
Reimplemented in Ogre::Material, and Ogre::UnifiedHighLevelGpuProgram.
Referenced by Ogre::Material::touch().
void Ogre::GLGpuNvparseProgram::unbindProgram (void) virtual
Execute the unbinding functions for this program.
Reimplemented from Ogre::GLGpuProgram.
virtual void Ogre::Resource::unload (void) virtual inherited
Unloads the resource; this is not permanent, the resource can be reloaded later if required.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
void Ogre::GLGpuNvparseProgram::unloadImpl (void) protected virtual
Unloads the resource; this is not permanent, the resource can be reloaded later if required.
Implements Ogre::Resource.
virtual void Ogre::Resource::unprepareImpl (void) inline protected virtual inherited
Internal function for undoing the 'prepare' action.
Called when the load is completed, and when resources are unloaded when they are prepared but not yet loaded.
Reimplemented in Ogre::Mesh, Ogre::D3D11Texture, Ogre::D3D9Texture, Ogre::Material, Ogre::GL3PlusTexture, and Ogre::GLTexture.
Member Data Documentation
GpuLogicalBufferStructPtr Ogre::GpuProgram::mBoolLogicalToPhysical mutable protected inherited
Record of logical to physical buffer maps.
Mandatory for low-level programs or high-level programs which set their params the same way. This is a shared pointer because if the program is recompiled and the parameters change, this definition will alter, but previous params may reference the old def.
bool Ogre::GpuProgram::mCompileError protected inherited
Did we encounter a compilation error?
Vector3 Ogre::GpuProgram::mComputeGroupDimensions protected inherited
The number of process groups dispatched by this (compute) program.
GpuNamedConstantsPtr Ogre::GpuProgram::mConstantDefs mutable protected inherited
Parameter name -> ConstantDefinition map, shared instance used by all parameter objects.
This is a shared pointer because if the program is recompiled and the parameters change, this definition will alter, but previous params may reference the old def.
ResourceManager* Ogre::Resource::mCreator protected inherited
Creator.
GpuProgramParametersSharedPtr Ogre::GpuProgram::mDefaultParams protected inherited
The default parameters for use with this object.
GpuLogicalBufferStructPtr Ogre::GpuProgram::mDoubleLogicalToPhysical mutable protected inherited
Record of logical to physical buffer maps.
Mandatory for low-level programs or high-level programs which set their params the same way. This is a shared pointer because if the program is recompiled and the parameters change, this definition will alter, but previous params may reference the old def.
String Ogre::GpuProgram::mFilename protected inherited
The name of the file to load source from (may be blank)
GpuLogicalBufferStructPtr Ogre::GpuProgram::mFloatLogicalToPhysical mutable protected inherited
Record of logical to physical buffer maps.
Mandatory for low-level programs or high-level programs which set their params the same way. This is a shared pointer because if the program is recompiled and the parameters change, this definition will alter, but previous params may reference the old def.
String Ogre::Resource::mGroup protected inherited
The name of the resource group.
ResourceHandle Ogre::Resource::mHandle protected inherited
Numeric handle for more efficient look up than name.
GpuLogicalBufferStructPtr Ogre::GpuProgram::mIntLogicalToPhysical mutable protected inherited
Record of logical to physical buffer maps.
Mandatory for low-level programs or high-level programs which set their params the same way. This is a shared pointer because if the program is recompiled and the parameters change, this definition will alter, but previous params may reference the old def.
volatile bool Ogre::Resource::mIsBackgroundLoaded protected inherited
Is this resource going to be background loaded? Only applicable for multithreaded.
bool Ogre::Resource::mIsManual protected inherited
Is this file manually loaded?
ListenerList Ogre::Resource::mListenerList protected inherited
bool Ogre::GpuProgram::mLoadedManualNamedConstants protected inherited
ManualResourceLoader* Ogre::Resource::mLoader protected inherited
Optional manual loader; if provided, data is loaded from here instead of a file.
bool Ogre::GpuProgram::mLoadFromFile protected inherited
Whether we need to load source from file or not.
AtomicScalar<LoadingState> Ogre::Resource::mLoadingState protected inherited
Is the resource currently loaded?
String Ogre::GpuProgram::mManualNamedConstantsFile protected inherited
File from which to load named constants manually.
bool Ogre::GpuProgram::mMorphAnimation protected inherited
Does this (vertex) program include morph animation?
String Ogre::Resource::mName protected inherited
Unique name of the resource.
bool Ogre::GpuProgram::mNeedsAdjacencyInfo protected inherited
Does this (geometry) program require adjacency information?
String Ogre::Resource::mOrigin protected inherited
Origin of this resource (e.g. script name) - optional.
ushort Ogre::GpuProgram::mPoseAnimation protected inherited
Does this (vertex) program include pose animation (count of number of poses supported)
GLenum Ogre::GLGpuProgram::mProgramType protected inherited
CmdAdjacency Ogre::GpuProgram::msAdjacencyCmd static protected inherited
CmdComputeGroupDims Ogre::GpuProgram::msComputeGroupDimsCmd static protected inherited
size_t Ogre::Resource::mSize protected inherited
The size of the resource in bytes.
bool Ogre::GpuProgram::mSkeletalAnimation protected inherited
Does this (vertex) program include skeletal animation?
CmdManualNamedConstsFile Ogre::GpuProgram::msManNamedConstsFileCmd static protected inherited
CmdMorph Ogre::GpuProgram::msMorphCmd static protected inherited
String Ogre::GpuProgram::mSource protected inherited
The assembler source of the program (may be blank until file loaded)
CmdPose Ogre::GpuProgram::msPoseCmd static protected inherited
CmdSkeletal Ogre::GpuProgram::msSkeletalCmd static protected inherited
CmdSyntax Ogre::GpuProgram::msSyntaxCmd static protected inherited
size_t Ogre::Resource::mStateCount protected inherited
State count, the number of times this resource has changed state.
CmdType Ogre::GpuProgram::msTypeCmd static protected inherited
CmdVTF Ogre::GpuProgram::msVTFCmd static protected inherited
String Ogre::GpuProgram::mSyntaxCode protected inherited
Syntax code e.g. arbvp1, vs_2_0 etc.
GpuProgramType Ogre::GpuProgram::mType protected inherited
The type of the program.
GpuLogicalBufferStructPtr Ogre::GpuProgram::mUIntLogicalToPhysical mutable protected inherited
Record of logical to physical buffer maps.
Mandatory for low-level programs or high-level programs which set their params the same way. This is a shared pointer because if the program is recompiled and the parameters change, this definition will alter, but previous params may reference the old def.
bool Ogre::GpuProgram::mVertexTextureFetch protected inherited
Does this (vertex) program require support for vertex texture fetch?
Ogre::Resource::OGRE_AUTO_MUTEX inherited
The documentation for this class was generated from the following file:
OgreGLGpuNvparseProgram.h