OGRE: Ogre::Volume::DualGridGenerator Class Reference
Ogre::Volume::DualGridGenerator Class Reference
Class for the generation of the DualGrid.
#include <OgreVolumeDualGridGenerator.h>
Public Member Functions
DualGridGenerator (void)
Constructor.
void generateDualGrid (const OctreeNode *root, IsoSurface *is, MeshBuilder *mb, Real maxMSDistance, const Vector3 &totalFrom, const Vector3 &totalTo, bool saveDualCells)
Generates the dualgrid of the given octree root node.
DualCell getDualCell (size_t i) const
Gets a dual cell.
size_t getDualCellCount (void) const
Gets the amount of generated dual cells.
Entity * getDualGrid (SceneManager *sceneManager)
Gets the lazily created entity of the dualgrid debug visualization.
Protected Member Functions
void addDualCell (const Vector3 &c0, const Vector3 &c1, const Vector3 &c2, const Vector3 &c3, const Vector3 &c4, const Vector3 &c5, const Vector3 &c6, const Vector3 &c7)
Adds a dualcell.
void addDualCell (const Vector3 &c0, const Vector3 &c1, const Vector3 &c2, const Vector3 &c3, const Vector3 &c4, const Vector3 &c5, const Vector3 &c6, const Vector3 &c7, Vector4 *values)
Adds a dualcell with precalculated values.
void createBorderCells (const OctreeNode *n0, const OctreeNode *n1, const OctreeNode *n2, const OctreeNode *n3, const OctreeNode *n4, const OctreeNode *n5, const OctreeNode *n6, const OctreeNode *n7)
void edgeProcX (const OctreeNode *n0, const OctreeNode *n1, const OctreeNode *n2, const OctreeNode *n3)
edgeProc with variing X of the nodes, see the paper for edgeProc().
void edgeProcY (const OctreeNode *n0, const OctreeNode *n1, const OctreeNode *n2, const OctreeNode *n3)
edgeProc with variing Y of the nodes, see the paper for edgeProc().
void edgeProcZ (const OctreeNode *n0, const OctreeNode *n1, const OctreeNode *n2, const OctreeNode *n3)
edgeProc with variing Z of the nodes, see the paper for edgeProc().
void faceProcXY (const OctreeNode *n0, const OctreeNode *n1)
void faceProcXZ (const OctreeNode *n0, const OctreeNode *n1)
void faceProcZY (const OctreeNode *n0, const OctreeNode *n1)
void nodeProc (const OctreeNode *n)
void vertProc (const OctreeNode *n0, const OctreeNode *n1, const OctreeNode *n2, const OctreeNode *n3, const OctreeNode *n4, const OctreeNode *n5, const OctreeNode *n6, const OctreeNode *n7)
Protected Attributes
VecDualCell mDualCells
Holds the generated dual cells of the grid.
Entity * mDualGrid
The entity for the debug visualization of the grid.
IsoSurface * mIs
To contour the dualcells.
Real mMaxMSDistance
The maximum distance where to generate the skirts.
MeshBuilder * mMb
To store the triangles of the contour.
OctreeNode const * mRoot
Starting node to generate the grid from.
bool mSaveDualCells
Whether to store the dualcells for later visualization.
Vector3 mTotalFrom
The global from.
Vector3 mTotalTo
The total to.
Static Protected Attributes
static size_t mDualGridI
To give the debug manual object an unique name.
Detailed Description
Class for the generation of the DualGrid.
Constructor & Destructor Documentation
Ogre::Volume::DualGridGenerator::DualGridGenerator (void)
Constructor.
Member Function Documentation
void Ogre::Volume::DualGridGenerator::addDualCell (const Vector3 & c0, const Vector3 & c1, const Vector3 & c2, const Vector3 & c3, const Vector3 & c4, const Vector3 & c5, const Vector3 & c6, const Vector3 & c7) inline protected
Adds a dualcell.
Parameters
c0 The first corner.
c1 The second corner.
c2 The third corner.
c3 The fourth corner.
c4 The fifth corner.
c5 The sixth corner.
c6 The seventh corner.
void Ogre::Volume::DualGridGenerator::addDualCell (const Vector3 & c0, const Vector3 & c1, const Vector3 & c2, const Vector3 & c3, const Vector3 & c4, const Vector3 & c5, const Vector3 & c6, const Vector3 & c7, Vector4 * values) inline protected
Adds a dualcell with precalculated values.
Parameters
c0 The first corner.
c1 The second corner.
c2 The third corner.
c3 The fourth corner.
c4 The fifth corner.
c5 The sixth corner.
c6 The seventh corner.
c7 The eighth corner.
values The (possible) values at the corners.
References Ogre::Volume::IsoSurface::addMarchingCubesTriangles(), Ogre::Volume::IsoSurface::addMarchingSquaresTriangles(), Ogre::Volume::OctreeNode::getFrom(), Ogre::Volume::OctreeNode::getTo(), Ogre::Volume::IsoSurface::MS_CORNERS_BACK, Ogre::Volume::IsoSurface::MS_CORNERS_BOTTOM, Ogre::Volume::IsoSurface::MS_CORNERS_FRONT, Ogre::Volume::IsoSurface::MS_CORNERS_LEFT, Ogre::Volume::IsoSurface::MS_CORNERS_RIGHT, Ogre::Volume::IsoSurface::MS_CORNERS_TOP, Ogre::Vector3::x, Ogre::Vector3::y, and Ogre::Vector3::z.
void Ogre::Volume::DualGridGenerator::createBorderCells (const OctreeNode * n0, const OctreeNode * n1, const OctreeNode * n2, const OctreeNode * n3, const OctreeNode * n4, const OctreeNode * n5, const OctreeNode * n6, const OctreeNode * n7) protected
void Ogre::Volume::DualGridGenerator::edgeProcX (const OctreeNode * n0, const OctreeNode * n1, const OctreeNode * n2, const OctreeNode * n3) protected
edgeProc with variing X of the nodes, see the paper for edgeProc().
Direction of parameters: Z+, Y around the clock (n0, n3, n7, n4 for example of the parent cell)
Parameters
n0 The first node.
n1 The second node.
n2 The third node.
n3 The fourth node.
void Ogre::Volume::DualGridGenerator::edgeProcY (const OctreeNode * n0, const OctreeNode * n1, const OctreeNode * n2, const OctreeNode * n3) protected
edgeProc with variing Y of the nodes, see the paper for edgeProc().
Direction of parameters: X+, Z around the clock (n0, n1, n2, n3 for example of the parent cell)
Parameters
n0 The first node.
n1 The second node.
n2 The third node.
n3 The fourth node.
void Ogre::Volume::DualGridGenerator::edgeProcZ (const OctreeNode * n0, const OctreeNode * n1, const OctreeNode * n2, const OctreeNode * n3) protected
edgeProc with variing Z of the nodes, see the paper for edgeProc().
Direction of parameters: X+, Y around the clock (n7, n6, n2, n3 for example of the parent cell)
Parameters
n0 The first node.
n1 The second node.
n2 The third node.
n3 The fourth node.
void Ogre::Volume::DualGridGenerator::faceProcXY (const OctreeNode * n0, const OctreeNode * n1) protected
void Ogre::Volume::DualGridGenerator::faceProcXZ (const OctreeNode * n0, const OctreeNode * n1) protected
void Ogre::Volume::DualGridGenerator::faceProcZY (const OctreeNode * n0, const OctreeNode * n1) protected
void Ogre::Volume::DualGridGenerator::generateDualGrid (const OctreeNode * root, IsoSurface * is, MeshBuilder * mb, Real maxMSDistance, const Vector3 & totalFrom, const Vector3 & totalTo, bool saveDualCells)
Generates the dualgrid of the given octree root node.
Parameters
root The octree root node.
is To contour the dualcells.
mb To store the triangles of the contour.
maxMSDistance The maximum distance to the isosurface where to generate skirts.
totalFrom The global from.
totalTo The global to.
saveDualCells Whether to save the generated dualcells of the generated dual cells.
DualCell Ogre::Volume::DualGridGenerator::getDualCell (size_t i) const inline
Gets a dual cell.
Parameters
i The index of the wanted dual cell.
Returns
The dual cell.
size_t Ogre::Volume::DualGridGenerator::getDualCellCount (void) const inline
Gets the amount of generated dual cells.
Returns
The amount of generated dual cells.
Entity* Ogre::Volume::DualGridGenerator::getDualGrid (SceneManager * sceneManager)
Gets the lazily created entity of the dualgrid debug visualization.
Parameters
sceneManager The scenemanager creating the entity.
Returns
The entity. Might be null if no dualcells are available.
void Ogre::Volume::DualGridGenerator::nodeProc (const OctreeNode * n) protected
void Ogre::Volume::DualGridGenerator::vertProc (const OctreeNode * n0, const OctreeNode * n1, const OctreeNode * n2, const OctreeNode * n3, const OctreeNode * n4, const OctreeNode * n5, const OctreeNode * n6, const OctreeNode * n7) protected
Member Data Documentation
VecDualCell Ogre::Volume::DualGridGenerator::mDualCells protected
Holds the generated dual cells of the grid.
Entity* Ogre::Volume::DualGridGenerator::mDualGrid protected
The entity for the debug visualization of the grid.
size_t Ogre::Volume::DualGridGenerator::mDualGridI static protected
To give the debug manual object an unique name.
IsoSurface* Ogre::Volume::DualGridGenerator::mIs protected
To contour the dualcells.
Real Ogre::Volume::DualGridGenerator::mMaxMSDistance protected
The maximum distance where to generate the skirts.
MeshBuilder* Ogre::Volume::DualGridGenerator::mMb protected
To store the triangles of the contour.
OctreeNode const* Ogre::Volume::DualGridGenerator::mRoot protected
Starting node to generate the grid from.
bool Ogre::Volume::DualGridGenerator::mSaveDualCells protected
Whether to store the dualcells for later visualization.
Vector3 Ogre::Volume::DualGridGenerator::mTotalFrom protected
The global from.
Vector3 Ogre::Volume::DualGridGenerator::mTotalTo protected
The total to.
The documentation for this class was generated from the following file:
OgreVolumeDualGridGenerator.h