OGRE: Ogre::LodInputProviderBuffer Class Reference
Ogre::LodInputProviderBuffer Class Reference
#include <OgreLodInputProviderBuffer.h>
Public Member Functions
LodInputProviderBuffer (MeshPtr mesh)
virtual void initData (LodData *data)
Called when the data should be filled with the input.
Protected Types
typedef vector< LodData::Vertex * >::type VertexLookupList
Protected Member Functions
void addIndexData (LodData *data, LodIndexBuffer &indexBuffer, bool useSharedVertexLookup, unsigned short submeshID)
template<typename IndexType >
void addIndexDataImpl (LodData *data, IndexType *iPos, const IndexType *iEnd, VertexLookupList &lookup, unsigned short submeshID)
void addTriangleToEdges (LodData *data, LodData::Triangle *triangle)
void addVertexData (LodData *data, LodVertexBuffer &vertexBuffer, bool useSharedVertexLookup)
void initialize (LodData *data)
bool isDuplicateTriangle (LodData::Triangle *triangle, LodData::Triangle *triangle2)
LodData::Triangle * isDuplicateTriangle (LodData::Triangle *triangle)
void printTriangle (LodData::Triangle *triangle, stringstream &str)
void tuneContainerSize (LodData *data)
Protected Attributes
LodInputBuffer mBuffer
VertexLookupList mSharedVertexLookup
VertexLookupList mVertexLookup
Member Typedef Documentation
typedef vector<LodData::Vertex*>::type Ogre::LodInputProviderBuffer::VertexLookupList protected
Constructor & Destructor Documentation
Ogre::LodInputProviderBuffer::LodInputProviderBuffer (MeshPtr mesh)
Member Function Documentation
void Ogre::LodInputProviderBuffer::addIndexData (LodData * data, LodIndexBuffer & indexBuffer, bool useSharedVertexLookup, unsigned short submeshID) protected
template<typename IndexType > void Ogre::LodInputProviderBuffer::addIndexDataImpl (LodData * data, IndexType * iPos, const IndexType * iEnd, VertexLookupList & lookup, unsigned short submeshID) inline protected
References Ogre::LodData::Triangle::computeNormal(), Ogre::LogManager::getSingleton(), Ogre::LodData::getVectorIDFromPointer(), Ogre::LodData::Triangle::isMalformed(), Ogre::LodData::Triangle::isRemoved, Ogre::LodData::mIndexBufferInfoList, Ogre::LodData::mTriangleList, OgreAssert, Ogre::LogManager::stream(), Ogre::LodData::Triangle::submeshID, Ogre::LodData::Triangle::vertex, and Ogre::LodData::Triangle::vertexID.
void Ogre::LodInputProvider::addTriangleToEdges (LodData * data, LodData::Triangle * triangle) protected inherited
void Ogre::LodInputProviderBuffer::addVertexData (LodData * data, LodVertexBuffer & vertexBuffer, bool useSharedVertexLookup) protected
virtual void Ogre::LodInputProviderBuffer::initData (LodData * data) virtual
Called when the data should be filled with the input.
Implements Ogre::LodInputProvider.
void Ogre::LodInputProviderBuffer::initialize (LodData * data) protected
bool Ogre::LodInputProvider::isDuplicateTriangle (LodData::Triangle * triangle, LodData::Triangle * triangle2) protected inherited
LodData::Triangle* Ogre::LodInputProvider::isDuplicateTriangle (LodData::Triangle * triangle) protected inherited
void Ogre::LodInputProvider::printTriangle (LodData::Triangle * triangle, stringstream & str) protected inherited
void Ogre::LodInputProviderBuffer::tuneContainerSize (LodData * data) protected
Member Data Documentation
LodInputBuffer Ogre::LodInputProviderBuffer::mBuffer protected
VertexLookupList Ogre::LodInputProviderBuffer::mSharedVertexLookup protected
VertexLookupList Ogre::LodInputProviderBuffer::mVertexLookup protected
The documentation for this class was generated from the following file:
OgreLodInputProviderBuffer.h