OGRE: Ogre::GL3PlusDefaultHardwareBufferManagerBase Class Reference
Ogre::GL3PlusDefaultHardwareBufferManagerBase Class Reference
Specialisation of HardwareBufferManager to emulate hardware buffers.
#include <OgreGL3PlusDefaultHardwareBufferManager.h>
Public Types
enum BufferLicenseType { BLT_MANUAL_RELEASE, BLT_AUTOMATIC_RELEASE }
Public Member Functions
GL3PlusDefaultHardwareBufferManagerBase ()
~GL3PlusDefaultHardwareBufferManagerBase ()
virtual void _forceReleaseBufferCopies (const HardwareVertexBufferSharedPtr &sourceBuffer)
Internal method that forces the release of copies of a given buffer.
virtual void _forceReleaseBufferCopies (HardwareVertexBuffer *sourceBuffer)
Internal method that forces the release of copies of a given buffer.
virtual void _freeUnusedBufferCopies (void)
Free all unused vertex buffer copies.
void _notifyCounterBufferDestroyed (HardwareCounterBuffer *buf)
Notification that at hardware counter buffer has been destroyed.
void _notifyIndexBufferDestroyed (HardwareIndexBuffer *buf)
Notification that a hardware index buffer has been destroyed.
void _notifyUniformBufferDestroyed (HardwareUniformBuffer *buf)
Notification that at hardware uniform buffer has been destroyed.
void _notifyVertexBufferDestroyed (HardwareVertexBuffer *buf)
Notification that a hardware vertex buffer has been destroyed.
virtual void _releaseBufferCopies (bool forceFreeUnused=false)
Internal method for releasing all temporary buffers which have been allocated using BLT_AUTOMATIC_RELEASE; is called by OGRE.
virtual HardwareVertexBufferSharedPtr allocateVertexBufferCopy (const HardwareVertexBufferSharedPtr &sourceBuffer, BufferLicenseType licenseType, HardwareBufferLicensee *licensee, bool copyData=false)
Allocates a copy of a given vertex buffer.
HardwareCounterBufferSharedPtr createCounterBuffer (size_t sizeBytes, HardwareBuffer::Usage usage, bool useShadowBuffer, const String &name="")
Create a counter buffer.
HardwareIndexBufferSharedPtr createIndexBuffer (HardwareIndexBuffer::IndexType itype, size_t numIndexes, HardwareBuffer::Usage usage, bool useShadowBuffer=false)
Create a hardware index buffer.
RenderToVertexBufferSharedPtr createRenderToVertexBuffer (void)
Create a render to vertex buffer.
HardwareUniformBufferSharedPtr createUniformBuffer (size_t sizeBytes, HardwareBuffer::Usage usage, bool useShadowBuffer, const String &name="")
Create a uniform buffer.
HardwareVertexBufferSharedPtr createVertexBuffer (size_t vertexSize, size_t numVerts, HardwareBuffer::Usage usage, bool useShadowBuffer=false)
Creates a vertex buffer.
virtual VertexBufferBinding * createVertexBufferBinding (void)
Creates a new VertexBufferBinding.
virtual VertexDeclaration * createVertexDeclaration (void)
Creates a new vertex declaration.
virtual void destroyVertexBufferBinding (VertexBufferBinding *binding)
Destroys a VertexBufferBinding.
virtual void destroyVertexDeclaration (VertexDeclaration *decl)
Destroys a vertex declaration.
virtual void registerVertexBufferSourceAndCopy (const HardwareVertexBufferSharedPtr &sourceBuffer, const HardwareVertexBufferSharedPtr &copy)
Registers a vertex buffer as a copy of another.
virtual void releaseVertexBufferCopy (const HardwareVertexBufferSharedPtr &bufferCopy)
Manually release a vertex buffer copy for others to subsequently use.
virtual void touchVertexBufferCopy (const HardwareVertexBufferSharedPtr &bufferCopy)
Tell engine that the vertex buffer copy intent to reuse.
Protected Types
typedef set< HardwareCounterBuffer * >::type CounterBufferList
typedef multimap< HardwareVertexBuffer *, HardwareVertexBufferSharedPtr >::type FreeTemporaryVertexBufferMap
Map from original buffer to temporary buffers.
typedef set< HardwareIndexBuffer * >::type IndexBufferList
typedef map< HardwareVertexBuffer *, VertexBufferLicense >::type TemporaryVertexBufferLicenseMap
Map from temporary buffer to details of a license.
typedef set< HardwareUniformBuffer * >::type UniformBufferList
typedef set< VertexBufferBinding * >::type VertexBufferBindingList
typedef set< HardwareVertexBuffer * >::type VertexBufferList
WARNING: The following two members should place before all other members.
typedef set< VertexDeclaration * >::type VertexDeclarationList
Protected Member Functions
virtual VertexBufferBinding * createVertexBufferBindingImpl (void)
Internal method for creates a new VertexBufferBinding, may be overridden by certain rendering APIs.
virtual VertexDeclaration * createVertexDeclarationImpl (void)
Internal method for creates a new vertex declaration, may be overridden by certain rendering APIs.
virtual void destroyAllBindings (void)
Internal method for destroys all vertex buffer bindings.
virtual void destroyAllDeclarations (void)
Internal method for destroys all vertex declarations.
virtual void destroyVertexBufferBindingImpl (VertexBufferBinding *binding)
Internal method for destroys a VertexBufferBinding, may be overridden by certain rendering APIs.
virtual void destroyVertexDeclarationImpl (VertexDeclaration *decl)
Internal method for destroys a vertex declaration, may be overridden by certain rendering APIs.
virtual HardwareVertexBufferSharedPtr makeBufferCopy (const HardwareVertexBufferSharedPtr &source, HardwareBuffer::Usage usage, bool useShadowBuffer)
Creates a new buffer as a copy of the source, does not copy data.
OGRE_MUTEX (mVertexBuffersMutex)
OGRE_MUTEX (mIndexBuffersMutex)
OGRE_MUTEX (mUniformBuffersMutex)
OGRE_MUTEX (mCounterBuffersMutex)
OGRE_MUTEX (mVertexDeclarationsMutex)
OGRE_MUTEX (mVertexBufferBindingsMutex)
OGRE_MUTEX (mTempBuffersMutex)
Protected Attributes
CounterBufferList mCounterBuffers
FreeTemporaryVertexBufferMap mFreeTempVertexBufferMap
Map of current available temp buffers.
IndexBufferList mIndexBuffers
TemporaryVertexBufferLicenseMap mTempVertexBufferLicenses
Map of currently licensed temporary buffers.
size_t mUnderUsedFrameCount
Number of frames elapsed since temporary buffers utilization was above half the available.
UniformBufferList mUniformBuffers
VertexBufferBindingList mVertexBufferBindings
VertexBufferList mVertexBuffers
VertexDeclarationList mVertexDeclarations
Static Protected Attributes
static const size_t EXPIRED_DELAY_FRAME_THRESHOLD
Frame delay for BLT_AUTOMATIC_RELEASE temporary buffers.
static const size_t UNDER_USED_FRAME_THRESHOLD
Number of frames to wait before free unused temporary buffers.
Detailed Description
Specialisation of HardwareBufferManager to emulate hardware buffers.
Remarks
You might want to instantiate this class if you want to utilise classes like MeshSerializer without having initialised the rendering system (which is required to create a 'real' hardware buffer manager).
Member Typedef Documentation
typedef set<HardwareCounterBuffer*>::type Ogre::HardwareBufferManagerBase::CounterBufferList protected inherited
typedef multimap<HardwareVertexBuffer*, HardwareVertexBufferSharedPtr>::type Ogre::HardwareBufferManagerBase::FreeTemporaryVertexBufferMap protected inherited
Map from original buffer to temporary buffers.
typedef set<HardwareIndexBuffer*>::type Ogre::HardwareBufferManagerBase::IndexBufferList protected inherited
typedef map<HardwareVertexBuffer*, VertexBufferLicense>::type Ogre::HardwareBufferManagerBase::TemporaryVertexBufferLicenseMap protected inherited
Map from temporary buffer to details of a license.
typedef set<HardwareUniformBuffer*>::type Ogre::HardwareBufferManagerBase::UniformBufferList protected inherited
typedef set<VertexBufferBinding*>::type Ogre::HardwareBufferManagerBase::VertexBufferBindingList protected inherited
typedef set<HardwareVertexBuffer*>::type Ogre::HardwareBufferManagerBase::VertexBufferList protected inherited
WARNING: The following two members should place before all other members.
Members destruct order is very important here, because destructing other members will cause notify back to this class, and then will access to this two members.
typedef set<VertexDeclaration*>::type Ogre::HardwareBufferManagerBase::VertexDeclarationList protected inherited
Member Enumeration Documentation
enum Ogre::HardwareBufferManagerBase::BufferLicenseType inherited
Enumerator
BLT_MANUAL_RELEASE
Licensee will only release buffer when it says so.
BLT_AUTOMATIC_RELEASE
Licensee can have license revoked.
Constructor & Destructor Documentation
Ogre::GL3PlusDefaultHardwareBufferManagerBase::GL3PlusDefaultHardwareBufferManagerBase ()
Ogre::GL3PlusDefaultHardwareBufferManagerBase::~GL3PlusDefaultHardwareBufferManagerBase ()
Member Function Documentation
virtual void Ogre::HardwareBufferManagerBase::_forceReleaseBufferCopies (const HardwareVertexBufferSharedPtr & sourceBuffer) virtual inherited
Internal method that forces the release of copies of a given buffer.
Remarks
This usually means that the buffer which the copies are based on has been changed in some fundamental way, and the owner of the original wishes to make that known so that new copies will reflect the changes.
Parameters
sourceBuffer The source buffer as a shared pointer. Any buffer copies created from the source buffer are deleted.
Reimplemented in Ogre::HardwareBufferManager.
Referenced by Ogre::HardwareBufferManager::_forceReleaseBufferCopies().
virtual void Ogre::HardwareBufferManagerBase::_forceReleaseBufferCopies (HardwareVertexBuffer * sourceBuffer) virtual inherited
Internal method that forces the release of copies of a given buffer.
Remarks
This usually means that the buffer which the copies are based on has been changed in some fundamental way, and the owner of the original wishes to make that known so that new copies will reflect the changes.
Parameters
sourceBuffer The source buffer as a pointer. Any buffer copies created from the source buffer are deleted.
Reimplemented in Ogre::HardwareBufferManager.
virtual void Ogre::HardwareBufferManagerBase::_freeUnusedBufferCopies (void) virtual inherited
Free all unused vertex buffer copies.
Remarks
This method free all temporary vertex buffers that not in used. In normally, temporary vertex buffers are subsequently stored and can be made available for other purposes later without incurring the cost of construction / destruction. But in some cases you want to free them to save hardware memory (e.g. application was runs in a long time, you might free temporary buffers periodically to avoid memory overload).
Reimplemented in Ogre::HardwareBufferManager.
Referenced by Ogre::HardwareBufferManager::_freeUnusedBufferCopies().
void Ogre::HardwareBufferManagerBase::_notifyCounterBufferDestroyed (HardwareCounterBuffer * buf) inherited
Notification that at hardware counter buffer has been destroyed.
Referenced by Ogre::HardwareBufferManager::_notifyConterBufferDestroyed().
void Ogre::HardwareBufferManagerBase::_notifyIndexBufferDestroyed (HardwareIndexBuffer * buf) inherited
Notification that a hardware index buffer has been destroyed.
Referenced by Ogre::HardwareBufferManager::_notifyIndexBufferDestroyed().
void Ogre::HardwareBufferManagerBase::_notifyUniformBufferDestroyed (HardwareUniformBuffer * buf) inherited
Notification that at hardware uniform buffer has been destroyed.
Referenced by Ogre::HardwareBufferManager::_notifyUniformBufferDestroyed().
void Ogre::HardwareBufferManagerBase::_notifyVertexBufferDestroyed (HardwareVertexBuffer * buf) inherited
Notification that a hardware vertex buffer has been destroyed.
Referenced by Ogre::HardwareBufferManager::_notifyVertexBufferDestroyed().
virtual void Ogre::HardwareBufferManagerBase::_releaseBufferCopies (bool forceFreeUnused = false) virtual inherited
Internal method for releasing all temporary buffers which have been allocated using BLT_AUTOMATIC_RELEASE; is called by OGRE.
Parameters
forceFreeUnused If true, free all unused temporary buffers. If false, auto detect and free all unused temporary buffers based on temporary buffers utilization.
Reimplemented in Ogre::HardwareBufferManager.
Referenced by Ogre::HardwareBufferManager::_releaseBufferCopies().
virtual HardwareVertexBufferSharedPtr Ogre::HardwareBufferManagerBase::allocateVertexBufferCopy (const HardwareVertexBufferSharedPtr & sourceBuffer, BufferLicenseType licenseType, HardwareBufferLicensee * licensee, bool copyData = false) virtual inherited
Allocates a copy of a given vertex buffer.
Remarks
This method allocates a temporary copy of an existing vertex buffer. This buffer is subsequently stored and can be made available for other purposes later without incurring the cost of construction / destruction.
Parameters
sourceBuffer The source buffer to use as a copy.
licenseType The type of license required on this buffer - automatic release causes this class to release licenses every frame so that they can be reallocated anew.
licensee Pointer back to the class requesting the copy, which must implement HardwareBufferLicense in order to be notified when the license expires.
copyData If true, the current data is copied as well as the structure of the buffer/
Reimplemented in Ogre::HardwareBufferManager.
Referenced by Ogre::HardwareBufferManager::allocateVertexBufferCopy().
HardwareCounterBufferSharedPtr Ogre::GL3PlusDefaultHardwareBufferManagerBase::createCounterBuffer (size_t sizeBytes, HardwareBuffer::Usage usage, bool useShadowBuffer, const String & name = "") virtual
Create a counter buffer.
Implements Ogre::HardwareBufferManagerBase.
HardwareIndexBufferSharedPtr Ogre::GL3PlusDefaultHardwareBufferManagerBase::createIndexBuffer (HardwareIndexBuffer::IndexType itype, size_t numIndexes, HardwareBuffer::Usage usage, bool useShadowBuffer = false) virtual
Create a hardware index buffer.
Implements Ogre::HardwareBufferManagerBase.
RenderToVertexBufferSharedPtr Ogre::GL3PlusDefaultHardwareBufferManagerBase::createRenderToVertexBuffer (void) virtual
Create a render to vertex buffer.
Implements Ogre::HardwareBufferManagerBase.
HardwareUniformBufferSharedPtr Ogre::GL3PlusDefaultHardwareBufferManagerBase::createUniformBuffer (size_t sizeBytes, HardwareBuffer::Usage usage, bool useShadowBuffer, const String & name = "") virtual
Create a uniform buffer.
Implements Ogre::HardwareBufferManagerBase.
HardwareVertexBufferSharedPtr Ogre::GL3PlusDefaultHardwareBufferManagerBase::createVertexBuffer (size_t vertexSize, size_t numVerts, HardwareBuffer::Usage usage, bool useShadowBuffer = false) virtual
Creates a vertex buffer.
Implements Ogre::HardwareBufferManagerBase.
virtual VertexBufferBinding* Ogre::HardwareBufferManagerBase::createVertexBufferBinding (void) virtual inherited
Creates a new VertexBufferBinding.
Reimplemented in Ogre::HardwareBufferManager.
Referenced by Ogre::HardwareBufferManager::createVertexBufferBinding().
virtual VertexBufferBinding* Ogre::HardwareBufferManagerBase::createVertexBufferBindingImpl (void) protected virtual inherited
Internal method for creates a new VertexBufferBinding, may be overridden by certain rendering APIs.
virtual VertexDeclaration* Ogre::HardwareBufferManagerBase::createVertexDeclaration (void) virtual inherited
Creates a new vertex declaration.
Reimplemented in Ogre::HardwareBufferManager.
Referenced by Ogre::HardwareBufferManager::createVertexDeclaration().
virtual VertexDeclaration* Ogre::HardwareBufferManagerBase::createVertexDeclarationImpl (void) protected virtual inherited
Internal method for creates a new vertex declaration, may be overridden by certain rendering APIs.
Reimplemented in Ogre::GLES2HardwareBufferManagerBase, Ogre::D3D11HardwareBufferManagerBase, and Ogre::D3D9HardwareBufferManagerBase.
virtual void Ogre::HardwareBufferManagerBase::destroyAllBindings (void) protected virtual inherited
Internal method for destroys all vertex buffer bindings.
virtual void Ogre::HardwareBufferManagerBase::destroyAllDeclarations (void) protected virtual inherited
Internal method for destroys all vertex declarations.
virtual void Ogre::HardwareBufferManagerBase::destroyVertexBufferBinding (VertexBufferBinding * binding) virtual inherited
Destroys a VertexBufferBinding.
Reimplemented in Ogre::HardwareBufferManager.
Referenced by Ogre::HardwareBufferManager::destroyVertexBufferBinding().
virtual void Ogre::HardwareBufferManagerBase::destroyVertexBufferBindingImpl (VertexBufferBinding * binding) protected virtual inherited
Internal method for destroys a VertexBufferBinding, may be overridden by certain rendering APIs.
virtual void Ogre::HardwareBufferManagerBase::destroyVertexDeclaration (VertexDeclaration * decl) virtual inherited
Destroys a vertex declaration.
Reimplemented in Ogre::HardwareBufferManager.
Referenced by Ogre::HardwareBufferManager::destroyVertexDeclaration().
virtual void Ogre::HardwareBufferManagerBase::destroyVertexDeclarationImpl (VertexDeclaration * decl) protected virtual inherited
Internal method for destroys a vertex declaration, may be overridden by certain rendering APIs.
Reimplemented in Ogre::GLES2HardwareBufferManagerBase, Ogre::D3D11HardwareBufferManagerBase, and Ogre::D3D9HardwareBufferManagerBase.
virtual HardwareVertexBufferSharedPtr Ogre::HardwareBufferManagerBase::makeBufferCopy (const HardwareVertexBufferSharedPtr & source, HardwareBuffer::Usage usage, bool useShadowBuffer) protected virtual inherited
Creates a new buffer as a copy of the source, does not copy data.
Ogre::HardwareBufferManagerBase::OGRE_MUTEX (mVertexBuffersMutex) protected inherited
Ogre::HardwareBufferManagerBase::OGRE_MUTEX (mIndexBuffersMutex) protected inherited
Ogre::HardwareBufferManagerBase::OGRE_MUTEX (mUniformBuffersMutex) protected inherited
Ogre::HardwareBufferManagerBase::OGRE_MUTEX (mCounterBuffersMutex) protected inherited
Ogre::HardwareBufferManagerBase::OGRE_MUTEX (mVertexDeclarationsMutex) protected inherited
Ogre::HardwareBufferManagerBase::OGRE_MUTEX (mVertexBufferBindingsMutex) protected inherited
Ogre::HardwareBufferManagerBase::OGRE_MUTEX (mTempBuffersMutex) protected inherited
virtual void Ogre::HardwareBufferManagerBase::registerVertexBufferSourceAndCopy (const HardwareVertexBufferSharedPtr & sourceBuffer, const HardwareVertexBufferSharedPtr & copy) virtual inherited
Registers a vertex buffer as a copy of another.
Remarks
This is useful for registering an existing buffer as a temporary buffer which can be allocated just like a copy.
Reimplemented in Ogre::HardwareBufferManager.
Referenced by Ogre::HardwareBufferManager::registerVertexBufferSourceAndCopy().
virtual void Ogre::HardwareBufferManagerBase::releaseVertexBufferCopy (const HardwareVertexBufferSharedPtr & bufferCopy) virtual inherited
Manually release a vertex buffer copy for others to subsequently use.
Remarks
Only required if the original call to allocateVertexBufferCopy included a licenseType of BLT_MANUAL_RELEASE.
Parameters
bufferCopy The buffer copy. The caller is expected to delete or at least no longer use this reference, since another user may well begin to modify the contents of the buffer.
Reimplemented in Ogre::HardwareBufferManager.
Referenced by Ogre::HardwareBufferManager::releaseVertexBufferCopy().
virtual void Ogre::HardwareBufferManagerBase::touchVertexBufferCopy (const HardwareVertexBufferSharedPtr & bufferCopy) virtual inherited
Tell engine that the vertex buffer copy intent to reuse.
Remarks
Ogre internal keep an expired delay counter of BLT_AUTOMATIC_RELEASE buffers, when the counter count down to zero, it'll release for other purposes later. But you can use this function to reset the counter to the internal configured value, keep the buffer not get released for some frames.
Parameters
bufferCopy The buffer copy. The caller is expected to keep this buffer copy for use.
Reimplemented in Ogre::HardwareBufferManager.
Referenced by Ogre::HardwareBufferManager::touchVertexBufferCopy().
Member Data Documentation
const size_t Ogre::HardwareBufferManagerBase::EXPIRED_DELAY_FRAME_THRESHOLD static protected inherited
Frame delay for BLT_AUTOMATIC_RELEASE temporary buffers.
CounterBufferList Ogre::HardwareBufferManagerBase::mCounterBuffers protected inherited
FreeTemporaryVertexBufferMap Ogre::HardwareBufferManagerBase::mFreeTempVertexBufferMap protected inherited
Map of current available temp buffers.
IndexBufferList Ogre::HardwareBufferManagerBase::mIndexBuffers protected inherited
TemporaryVertexBufferLicenseMap Ogre::HardwareBufferManagerBase::mTempVertexBufferLicenses protected inherited
Map of currently licensed temporary buffers.
size_t Ogre::HardwareBufferManagerBase::mUnderUsedFrameCount protected inherited
Number of frames elapsed since temporary buffers utilization was above half the available.
UniformBufferList Ogre::HardwareBufferManagerBase::mUniformBuffers protected inherited
VertexBufferBindingList Ogre::HardwareBufferManagerBase::mVertexBufferBindings protected inherited
VertexBufferList Ogre::HardwareBufferManagerBase::mVertexBuffers protected inherited
VertexDeclarationList Ogre::HardwareBufferManagerBase::mVertexDeclarations protected inherited
const size_t Ogre::HardwareBufferManagerBase::UNDER_USED_FRAME_THRESHOLD static protected inherited
Number of frames to wait before free unused temporary buffers.
The documentation for this class was generated from the following file:
OgreGL3PlusDefaultHardwareBufferManager.h