OGRE: Ogre::Font Class Reference
Ogre::Font Class Reference
Core » Resources
Class representing a font in the system.
#include <OgreFont.h>
Classes
class CmdCharSpacer
class CmdCodePoints
Command object for Font - see ParamCommand.
class CmdResolution
Command object for Font - see ParamCommand.
class CmdSize
Command object for Font - see ParamCommand.
class CmdSource
Command object for Font - see ParamCommand.
class CmdType
Command object for Font - see ParamCommand.
struct GlyphInfo
Information about the position and size of a glyph in a texture.
Public Types
typedef Ogre::uint32 CodePoint
typedef std::pair< CodePoint, CodePoint > CodePointRange
A range of code points, inclusive on both ends.
typedef vector< CodePointRange >::type CodePointRangeList
enum LoadingFlags {
LF_DEFAULT = 0, LF_INCLUDE_NON_RELOADABLE = 1, LF_ONLY_UNREFERENCED = 2, LF_ONLY_UNREFERENCED_INCLUDE_NON_RELOADABLE = 3,
LF_PRESERVE_STATE = 4
}
Enum that allow to choose subset of unloaded/reloaded resources and to adjust reloading behavior.
enum LoadingState {
LOADSTATE_UNLOADED, LOADSTATE_LOADING, LOADSTATE_LOADED, LOADSTATE_UNLOADING,
LOADSTATE_PREPARED, LOADSTATE_PREPARING
}
Enum identifying the loading state of the resource.
typedef Ogre::FloatRect UVRect
Public Member Functions
Font (ResourceManager *creator, const String &name, ResourceHandle handle, const String &group, bool isManual=false, ManualResourceLoader *loader=0)
Constructor.
virtual ~Font ()
virtual void _dirtyState ()
Manually mark the state of this resource as having been changed.
virtual void _fireLoadingComplete (bool wasBackgroundLoaded)
Firing of loading complete event.
virtual void _firePreparingComplete (bool wasBackgroundLoaded)
Firing of preparing complete event.
virtual void _fireUnloadingComplete (void)
Firing of unloading complete event.
virtual void _notifyOrigin (const String &origin)
Notify this resource of it's origin.
void addCodePointRange (const CodePointRange &range)
Adds a range of code points to the list of code point ranges to generate glyphs for, if this is a truetype based font.
virtual void addListener (Listener *lis)
Register a listener on this resource.
virtual void changeGroupOwnership (const String &newGroup)
Change the resource group ownership of a Resource.
void clearCodePointRanges ()
Clear the list of code point ranges.
virtual void copyParametersTo (StringInterface *dest) const
Method for copying this object's parameters to another object.
virtual void escalateLoading ()
Escalates the loading of a background loaded resource.
bool getAntialiasColour (void) const
Gets whether or not the colour of this font is antialiased as it is generated from a true type font.
uint getCharacterSpacer (void) const
Gets the spacing to allocate for font characters to overlap each other.
const CodePointRangeList & getCodePointRangeList () const
Get a const reference to the list of code point ranges to be used to generate glyphs from a truetype font.
virtual ResourceManager * getCreator (void)
Gets the manager which created this resource.
Real getGlyphAspectRatio (CodePoint id) const
Gets the aspect ratio (width / height) of this character.
const GlyphInfo & getGlyphInfo (CodePoint id) const
Gets the information available for a glyph corresponding to a given code point, or throws an exception if it doesn't exist;.
const UVRect & getGlyphTexCoords (CodePoint id) const
Returns the texture coordinates of the associated glyph.
virtual const String & getGroup (void) const
Gets the group which this resource is a member of.
virtual ResourceHandle getHandle (void) const
virtual LoadingState getLoadingState () const
Returns the current loading state.
const MaterialPtr & getMaterial () const
Gets the material generated for this font, as a weak reference.
const MaterialPtr & getMaterial ()
Gets the material generated for this font, as a weak reference.
virtual const String & getName (void) const
Gets resource name.
virtual const String & getOrigin (void) const
Get the origin of this resource, e.g.
ParamDictionary * getParamDictionary (void)
Retrieves the parameter dictionary for this class.
const ParamDictionary * getParamDictionary (void) const
virtual String getParameter (const String &name) const
Generic parameter retrieval method.
const ParameterList & getParameters (void) const
Retrieves a list of parameters valid for this object.
virtual size_t getSize (void) const
Retrieves info about the size of the resource.
const String & getSource (void) const
Gets the source this font (either an image or a truetype font).
virtual size_t getStateCount () const
Returns the number of times this resource has changed state, which generally means the number of times it has been loaded.
int getTrueTypeMaxBearingY () const
Gets the maximum baseline distance of all glyphs used in the texture.
uint getTrueTypeResolution (void) const
Gets the resolution (dpi) of the font used to generate the texture.
Real getTrueTypeSize (void) const
Gets the point size of the font used to generate the texture.
FontType getType (void) const
Gets the type of font.
virtual bool isBackgroundLoaded (void) const
Returns whether this Resource has been earmarked for background loading.
virtual bool isLoaded (void) const
Returns true if the Resource has been loaded, false otherwise.
virtual bool isLoading () const
Returns whether the resource is currently in the process of background loading.
virtual bool isManuallyLoaded (void) const
Is this resource manually loaded?
virtual bool isPrepared (void) const
Returns true if the Resource has been prepared, false otherwise.
virtual bool isReloadable (void) const
Returns true if the Resource is reloadable, false otherwise.
virtual void load (bool backgroundThread=false)
Loads the resource, if it is not already.
void loadResource (Resource *resource)
Implementation of ManualResourceLoader::loadResource, called when the Texture that this font creates needs to (re)load.
virtual void prepare (bool backgroundThread=false)
Prepares the resource for load, if it is not already.
virtual void prepareResource (Resource *resource)
Called when a resource wishes to load.
virtual void reload (LoadingFlags flags=LF_DEFAULT)
Reloads the resource, if it is already loaded.
virtual void removeListener (Listener *lis)
Remove a listener on this resource.
void setAntialiasColour (bool enabled)
Sets whether or not the colour of this font is antialiased as it is generated from a true type font.
virtual void setBackgroundLoaded (bool bl)
Tells the resource whether it is background loaded or not.
void setCharacterSpacer (uint charSpacer)
Sets the spacing to allocate for font characters to overlap each other.
void setGlyphAspectRatio (CodePoint id, Real ratio)
Sets the aspect ratio (width / height) of this character.
void setGlyphTexCoords (CodePoint id, Real u1, Real v1, Real u2, Real v2, Real textureAspect)
Sets the texture coordinates of a glyph.
virtual void setManuallyLoaded (bool isManual)
Set "Is this resource manually loaded?".
virtual bool setParameter (const String &name, const String &value)
Generic parameter setting method.
virtual void setParameterList (const NameValuePairList &paramList)
Generic multiple parameter setting method.
void setSource (const String &source)
Sets the source of the font.
virtual void setToLoaded (void)
Change the Resource loading state to loaded.
void setTrueTypeResolution (uint ttfResolution)
Gets the resolution (dpi) of the font used to generate the texture (only required for FT_TRUETYPE).
void setTrueTypeSize (Real ttfSize)
Sets the size of a truetype font (only required for FT_TRUETYPE).
void setType (FontType ftype)
Sets the type of font.
virtual void touch (void)
'Touches' the resource to indicate it has been used.
virtual void unload (void)
Unloads the resource; this is not permanent, the resource can be reloaded later if required.
Static Public Member Functions
static void cleanupDictionary ()
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
Public Attributes
OGRE_AUTO_MUTEX
Protected Types
typedef map< CodePoint, GlyphInfo >::type CodePointMap
Map from unicode code point to texture coordinates.
typedef set< Listener * >::type ListenerList
Protected Member Functions
size_t calculateSize (void) const
Calculate the size of a resource; this will only be called after 'load'.
bool createParamDictionary (const String &className)
Internal method for creating a parameter dictionary for the class, if it does not already exist.
void createTextureFromFont (void)
Internal method for loading from ttf.
virtual void loadImpl ()
Internal implementation of the meat of the 'load' action, only called if this resource is not being loaded from a ManualResourceLoader.
OGRE_MUTEX (mListenerListMutex)
virtual void postLoadImpl (void)
Internal hook to perform actions after the load process, but before the resource has been marked as fully loaded.
virtual void postUnloadImpl (void)
Internal hook to perform actions after the unload process, but before the resource has been marked as fully unloaded.
virtual void preLoadImpl (void)
Internal hook to perform actions before the load process, but after the resource has been marked as 'loading'.
virtual void prepareImpl (void)
Internal implementation of the meat of the 'prepare' action.
virtual void preUnloadImpl (void)
Internal hook to perform actions before the unload process.
virtual void unloadImpl ()
Internal implementation of the 'unload' action; called regardless of whether this resource is being loaded from a ManualResourceLoader.
virtual void unprepareImpl (void)
Internal function for undoing the 'prepare' action.
Protected Attributes
bool mAntialiasColour
For TRUE_TYPE font only.
uint mCharacterSpacer
Add a gap between letters vertically and horizonally prevents nasty artifacts caused by fonts atypically wide or tall characters.
CodePointMap mCodePointMap
CodePointRangeList mCodePointRangeList
Range of code points to generate glyphs for (truetype only)
ResourceManager * mCreator
Creator.
String mGroup
The name of the resource group.
ResourceHandle mHandle
Numeric handle for more efficient look up than name.
volatile bool mIsBackgroundLoaded
Is this resource going to be background loaded? Only applicable for multithreaded.
bool mIsManual
Is this file manually loaded?
ListenerList mListenerList
ManualResourceLoader * mLoader
Optional manual loader; if provided, data is loaded from here instead of a file.
AtomicScalar< LoadingState > mLoadingState
Is the resource currently loaded?
MaterialPtr mMaterial
The material which is generated for this font.
String mName
Unique name of the resource.
String mOrigin
Origin of this resource (e.g. script name) - optional.
size_t mSize
The size of the resource in bytes.
String mSource
Source of the font (either an image name or a truetype font)
size_t mStateCount
State count, the number of times this resource has changed state.
TexturePtr mTexture
Texture pointer.
int mTtfMaxBearingY
Max distance to baseline of this (truetype) font.
uint mTtfResolution
Resolution (dpi) of truetype font.
Real mTtfSize
Size of the truetype font, in points.
FontType mType
The type of font.
Static Protected Attributes
static CmdCharSpacer msCharacterSpacerCmd
static CmdCodePoints msCodePointsCmd
static CmdResolution msResolutionCmd
static CmdSize msSizeCmd
static CmdSource msSourceCmd
static CmdType msTypeCmd
Detailed Description
Class representing a font in the system.
Remarks
This class is simply a way of getting a font texture into the OGRE system and to easily retrieve the texture coordinates required to accurately render them. Fonts can either be loaded from precreated textures, or the texture can be generated using a truetype font. You can either create the texture manually in code, or you can use a .fontdef script to define it (probably more practical since you can reuse the definition more easily)
Note
This class extends both Resource and ManualResourceLoader since it is both a resource in it's own right, but it also provides the manual load implementation for the Texture it creates.
Member Typedef Documentation
typedef Ogre::uint32 Ogre::Font::CodePoint
typedef map<CodePoint, GlyphInfo>::type Ogre::Font::CodePointMap protected
Map from unicode code point to texture coordinates.
typedef std::pair<CodePoint, CodePoint> Ogre::Font::CodePointRange
A range of code points, inclusive on both ends.
typedef vector<CodePointRange>::type Ogre::Font::CodePointRangeList
typedef set<Listener*>::type Ogre::Resource::ListenerList protected inherited
typedef Ogre::FloatRect Ogre::Font::UVRect
Member Enumeration Documentation
enum Ogre::Resource::LoadingFlags inherited
Enum that allow to choose subset of unloaded/reloaded resources and to adjust reloading behavior.
Enumerator
LF_DEFAULT
Only reloadable resources are processed, reload restores initial state.
LF_INCLUDE_NON_RELOADABLE
Process non-reloadable resources too.
LF_ONLY_UNREFERENCED
Process only resources which are not referenced by any other object. Usefull to reduce resource consumption.
LF_ONLY_UNREFERENCED_INCLUDE_NON_RELOADABLE
Combination of LF_ONLY_UNREFERENCED and LF_INCLUDE_NON_RELOADABLE.
LF_PRESERVE_STATE
Preserve some states during reloading, for example stencil shadows prepareness for Meshes.
enum Ogre::Resource::LoadingState inherited
Enum identifying the loading state of the resource.
Enumerator
LOADSTATE_UNLOADED
Not loaded.
LOADSTATE_LOADING
Loading is in progress.
LOADSTATE_LOADED
Fully loaded.
LOADSTATE_UNLOADING
Currently unloading.
LOADSTATE_PREPARED
Fully prepared.
LOADSTATE_PREPARING
Preparing is in progress.
Constructor & Destructor Documentation
Ogre::Font::Font (ResourceManager * creator, const String & name, ResourceHandle handle, const String & group, bool isManual = false, ManualResourceLoader * loader = 0)
Constructor.
See also
Resource
virtual Ogre::Font::~Font () virtual
Member Function Documentation
virtual void Ogre::Resource::_dirtyState () virtual inherited
Manually mark the state of this resource as having been changed.
Remarks
You only need to call this from outside if you explicitly want derived objects to think this object has changed.
See also
getStateCount.
virtual void Ogre::Resource::_fireLoadingComplete (bool wasBackgroundLoaded) virtual inherited
Firing of loading complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
Parameters
wasBackgroundLoaded Whether this was a background loaded event
virtual void Ogre::Resource::_firePreparingComplete (bool wasBackgroundLoaded) virtual inherited
Firing of preparing complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
Parameters
wasBackgroundLoaded Whether this was a background loaded event
virtual void Ogre::Resource::_fireUnloadingComplete (void) virtual inherited
Firing of unloading complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
virtual void Ogre::Resource::_notifyOrigin (const String & origin) inline virtual inherited
Notify this resource of it's origin.
void Ogre::Font::addCodePointRange (const CodePointRange & range) inline
Adds a range of code points to the list of code point ranges to generate glyphs for, if this is a truetype based font.
Remarks
In order to save texture space, only the glyphs which are actually needed by the application are generated into the texture. Before this object is loaded you must call this method as many times as necessary to define the code point range that you need.
virtual void Ogre::Resource::addListener (Listener * lis) virtual inherited
Register a listener on this resource.
See also
Resource::Listener
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
size_t Ogre::Font::calculateSize (void) const inline protected virtual
Calculate the size of a resource; this will only be called after 'load'.
Reimplemented from Ogre::Resource.
virtual void Ogre::Resource::changeGroupOwnership (const String & newGroup) virtual inherited
Change the resource group ownership of a Resource.
Remarks
This method is generally reserved for internal use, although if you really know what you're doing you can use it to move this resource from one group to another.
Parameters
newGroup Name of the new group
static void Ogre::StringInterface::cleanupDictionary () static inherited
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
MaterialManager) initializes.
void Ogre::Font::clearCodePointRanges () inline
Clear the list of code point ranges.
virtual void Ogre::StringInterface::copyParametersTo (StringInterface * dest) const inline virtual inherited
Method for copying this object's parameters to another object.
Remarks
This method takes the values of all the object's parameters and tries to set the same values on the destination object. This provides a completely type independent way to copy parameters to other objects. Note that because of the String manipulation involved, this should not be regarded as an efficient process and should be saved for times outside of the rendering loop.
Any unrecognised parameters will be ignored as with setParameter method.
Parameters
dest Pointer to object to have it's parameters set the same as this object.
References Ogre::ParamDictionary::mParamDefs, and Ogre::StringInterface::setParameter().
bool Ogre::StringInterface::createParamDictionary (const String & className) inline protected inherited
Internal method for creating a parameter dictionary for the class, if it does not already exist.
Remarks
This method will check to see if a parameter dictionary exist for this class yet, and if not will create one. NB you must supply the name of the class (RTTI is not used or performance).
Parameters
className the name of the class using the dictionary
Returns
true if a new dictionary was created, false if it was already there
References OGRE_LOCK_MUTEX.
void Ogre::Font::createTextureFromFont (void) protected
Internal method for loading from ttf.
virtual void Ogre::Resource::escalateLoading () virtual inherited
Escalates the loading of a background loaded resource.
Remarks
If a resource is set to load in the background, but something needs it before it's been loaded, there could be a problem. If the user of this resource really can't wait, they can escalate the loading which basically pulls the loading into the current thread immediately. If the resource is already being loaded but just hasn't quite finished then this method will simply wait until the background load is complete.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
bool Ogre::Font::getAntialiasColour (void) const inline
Gets whether or not the colour of this font is antialiased as it is generated from a true type font.
uint Ogre::Font::getCharacterSpacer (void) const
Gets the spacing to allocate for font characters to overlap each other.
Remarks
Returns the size of the character spacer, in points. A higher value allows for more stretched-out fonts. A low value reduces memory and processing time. The default is "5".
const CodePointRangeList& Ogre::Font::getCodePointRangeList () const inline
Get a const reference to the list of code point ranges to be used to generate glyphs from a truetype font.
virtual ResourceManager* Ogre::Resource::getCreator (void) inline virtual inherited
Gets the manager which created this resource.
Real Ogre::Font::getGlyphAspectRatio (CodePoint id) const inline
Gets the aspect ratio (width / height) of this character.
const GlyphInfo& Ogre::Font::getGlyphInfo (CodePoint id) const
Gets the information available for a glyph corresponding to a given code point, or throws an exception if it doesn't exist;.
const UVRect& Ogre::Font::getGlyphTexCoords (CodePoint id) const inline
Returns the texture coordinates of the associated glyph.
Remarks
Parameter is a short to allow both ASCII and wide chars.
Parameters
id The code point (unicode)
Returns
A rectangle with the UV coordinates, or null UVs if the code point was not present
virtual const String& Ogre::Resource::getGroup (void) const inline virtual inherited
Gets the group which this resource is a member of.
Reimplemented in Ogre::SkeletonInstance.
virtual ResourceHandle Ogre::Resource::getHandle (void) const inline virtual inherited
Reimplemented in Ogre::SkeletonInstance.
virtual LoadingState Ogre::Resource::getLoadingState () const inline virtual inherited
Returns the current loading state.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::get().
const MaterialPtr& Ogre::Font::getMaterial () const inline
Gets the material generated for this font, as a weak reference.
Remarks
This will only be valid after the Font has been loaded.
const MaterialPtr& Ogre::Font::getMaterial () inline
Gets the material generated for this font, as a weak reference.
Remarks
This will only be valid after the Font has been loaded.
virtual const String& Ogre::Resource::getName (void) const inline virtual inherited
Gets resource name.
Reimplemented in Ogre::SkeletonInstance.
Referenced by Ogre::GpuProgramUsage::getProgramName(), and OgreBites::TrayManager::resourceLoadStarted().
virtual const String& Ogre::Resource::getOrigin (void) const inline virtual inherited
Get the origin of this resource, e.g.
a script file name.
Remarks
This property will only contain something if the creator of this resource chose to populate it. Script loaders are advised to populate it.
ParamDictionary* Ogre::StringInterface::getParamDictionary (void) inline inherited
Retrieves the parameter dictionary for this class.
Remarks
Only valid to call this after createParamDictionary.
Returns
Pointer to ParamDictionary shared by all instances of this class which you can add parameters to, retrieve parameters etc.
const ParamDictionary* Ogre::StringInterface::getParamDictionary (void) const inline inherited
virtual String Ogre::StringInterface::getParameter (const String & name) const inline virtual inherited
Generic parameter retrieval method.
Remarks
Call this method with the name of a parameter to retrieve a string-format value of the parameter in question. If in doubt, check the parameter definition in the list returned from getParameters for the type of this parameter. If you like you can use StringConverter to convert this string back into a native type.
Parameters
name The name of the parameter to get
Returns
String value of parameter, blank if not found
References Ogre::ParamCommand::doGet(), and Ogre::ParamDictionary::getParamCommand().
const ParameterList& Ogre::StringInterface::getParameters (void) const inherited
Retrieves a list of parameters valid for this object.
Returns
A reference to a static list of ParameterDef objects.
virtual size_t Ogre::Resource::getSize (void) const inline virtual inherited
Retrieves info about the size of the resource.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
const String& Ogre::Font::getSource (void) const
Gets the source this font (either an image or a truetype font).
virtual size_t Ogre::Resource::getStateCount () const inline virtual inherited
Returns the number of times this resource has changed state, which generally means the number of times it has been loaded.
Objects that build derived data based on the resource can check this value against a copy they kept last time they built this derived data, in order to know whether it needs rebuilding. This is a nice way of monitoring changes without having a tightly-bound callback.
int Ogre::Font::getTrueTypeMaxBearingY () const
Gets the maximum baseline distance of all glyphs used in the texture.
Remarks
Only applicable for FT_TRUETYPE Font objects. The baseline is the vertical origin of horizontal based glyphs. The bearingY attribute is the distance from the baseline (origin) to the top of the glyph's bounding box.
Note
This value is only available after the font has been loaded.
uint Ogre::Font::getTrueTypeResolution (void) const
Gets the resolution (dpi) of the font used to generate the texture.
Remarks
Only applicable for FT_TRUETYPE Font objects.
Real Ogre::Font::getTrueTypeSize (void) const
Gets the point size of the font used to generate the texture.
Remarks
Only applicable for FT_TRUETYPE Font objects. Note that the size of the font does not affect how big it is on the screen, just how large it is in the texture and thus how detailed it is.
FontType Ogre::Font::getType (void) const
Gets the type of font.
virtual bool Ogre::Resource::isBackgroundLoaded (void) const inline virtual inherited
Returns whether this Resource has been earmarked for background loading.
Remarks
This option only makes sense when you have built Ogre with thread support (OGRE_THREAD_SUPPORT). If a resource has been marked for background loading, then it won't load on demand like normal when load() is called. Instead, it will ignore request to load() except if the caller indicates it is the background loader. Any other users of this resource should check isLoaded(), and if that returns false, don't use the resource and come back later.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual bool Ogre::Resource::isLoaded (void) const inline virtual inherited
Returns true if the Resource has been loaded, false otherwise.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::get().
virtual bool Ogre::Resource::isLoading () const inline virtual inherited
Returns whether the resource is currently in the process of background loading.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::get().
virtual bool Ogre::Resource::isManuallyLoaded (void) const inline virtual inherited
Is this resource manually loaded?
virtual bool Ogre::Resource::isPrepared (void) const inline virtual inherited
Returns true if the Resource has been prepared, false otherwise.
References Ogre::AtomicScalar< T >::get().
virtual bool Ogre::Resource::isReloadable (void) const inline virtual inherited
Returns true if the Resource is reloadable, false otherwise.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::Resource::load (bool backgroundThread = false) virtual inherited
Loads the resource, if it is not already.
Remarks
If the resource is loaded from a file, loading is automatic. If not, if for example this resource gained it's data from procedural calls rather than loading from a file, then this resource will not reload on it's own.
Parameters
backgroundThread Indicates whether the caller of this method is the background resource loading thread.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::Font::loadImpl () protected virtual
Internal implementation of the meat of the 'load' action, only called if this resource is not being loaded from a ManualResourceLoader.
Implements Ogre::Resource.
void Ogre::Font::loadResource (Resource * resource) virtual
Implementation of ManualResourceLoader::loadResource, called when the Texture that this font creates needs to (re)load.
Implements Ogre::ManualResourceLoader.
Ogre::Resource::OGRE_MUTEX (mListenerListMutex) protected inherited
virtual void Ogre::Resource::postLoadImpl (void) inline protected virtual inherited
Internal hook to perform actions after the load process, but before the resource has been marked as fully loaded.
Note
Mutex will have already been acquired by the loading thread. Also, this call will occur even when using a ManualResourceLoader (when loadImpl is not actually called)
Reimplemented in Ogre::Mesh, Ogre::D3D11Texture, and Ogre::D3D9Texture.
virtual void Ogre::Resource::postUnloadImpl (void) inline protected virtual inherited
Internal hook to perform actions after the unload process, but before the resource has been marked as fully unloaded.
Note
Mutex will have already been acquired by the unloading thread.
virtual void Ogre::Resource::preLoadImpl (void) inline protected virtual inherited
Internal hook to perform actions before the load process, but after the resource has been marked as 'loading'.
Note
Mutex will have already been acquired by the loading thread. Also, this call will occur even when using a ManualResourceLoader (when loadImpl is not actually called)
virtual void Ogre::Resource::prepare (bool backgroundThread = false) virtual inherited
Prepares the resource for load, if it is not already.
One can call prepare() before load(), but this is not required as load() will call prepare() itself, if needed. When OGRE_THREAD_SUPPORT==1 both load() and prepare() are thread-safe. When OGRE_THREAD_SUPPORT==2 however, only prepare() is thread-safe. The reason for this function is to allow a background thread to do some of the loading work, without requiring the whole render system to be thread-safe. The background thread would call prepare() while the main render loop would later call load(). So long as prepare() remains thread-safe, subclasses can arbitrarily split the work of loading a resource between load() and prepare(). It is best to try and do as much work in prepare(), however, since this will leave less work for the main render thread to do and thus increase FPS.
Parameters
backgroundThread Whether this is occurring in a background thread
virtual void Ogre::Resource::prepareImpl (void) inline protected virtual inherited
Internal implementation of the meat of the 'prepare' action.
Reimplemented in Ogre::Mesh, Ogre::D3D11Texture, Ogre::D3D9Texture, Ogre::Material, Ogre::PatchMesh, Ogre::GL3PlusTexture, and Ogre::GLTexture.
virtual void Ogre::ManualResourceLoader::prepareResource (Resource * resource) inline virtual inherited
Called when a resource wishes to load.
Note that this could get called in a background thread even in just a semithreaded ogre (OGRE_THREAD_SUPPORT==2). Thus, you must not access the rendersystem from this callback. Do that stuff in loadResource.
Parameters
resource The resource which wishes to load
virtual void Ogre::Resource::preUnloadImpl (void) inline protected virtual inherited
Internal hook to perform actions before the unload process.
Note
Mutex will have already been acquired by the unloading thread.
virtual void Ogre::Resource::reload (LoadingFlags flags = LF_DEFAULT) virtual inherited
Reloads the resource, if it is already loaded.
Remarks
Calls unload() and then load() again, if the resource is already loaded. If it is not loaded already, then nothing happens.
Reimplemented in Ogre::Mesh, and Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::Resource::removeListener (Listener * lis) virtual inherited
Remove a listener on this resource.
See also
Resource::Listener
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
void Ogre::Font::setAntialiasColour (bool enabled) inline
Sets whether or not the colour of this font is antialiased as it is generated from a true type font.
Remarks
This is valid only for a FT_TRUETYPE font. If you are planning on using alpha blending to draw your font, then it is a good idea to set this to false (which is the default), otherwise the darkening of the font will combine with the fading out of the alpha around the edges and make your font look thinner than it should. However, if you intend to blend your font using a colour blending mode (add or modulate for example) then it's a good idea to set this to true, in order to soften your font edges.
virtual void Ogre::Resource::setBackgroundLoaded (bool bl) inline virtual inherited
Tells the resource whether it is background loaded or not.
See also
Resource::isBackgroundLoaded. Note that calling this only defers the normal on-demand loading behaviour of a resource, it does not actually set up a thread to make sure the resource gets loaded in the background. You should use ResourceBackgroundLoadingQueue to manage the actual loading (which will call this method itself).
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
void Ogre::Font::setCharacterSpacer (uint charSpacer)
Sets the spacing to allocate for font characters to overlap each other.
Parameters
charSpacer The size of the character spacer, in points. Increasing it allows for more stretched-out fonts; decreasing it reduces memory and processing time. The default is "5".
void Ogre::Font::setGlyphAspectRatio (CodePoint id, Real ratio) inline
Sets the aspect ratio (width / height) of this character.
Remarks
You only need to call this if you're setting up a font loaded from a texture manually.
void Ogre::Font::setGlyphTexCoords (CodePoint id, Real u1, Real v1, Real u2, Real v2, Real textureAspect) inline
Sets the texture coordinates of a glyph.
Remarks
You only need to call this if you're setting up a font loaded from a texture manually.
Note
Also sets the aspect ratio (width / height) of this character. textureAspect is the width/height of the texture (may be non-square)
virtual void Ogre::Resource::setManuallyLoaded (bool isManual) inline virtual inherited
Set "Is this resource manually loaded?".
virtual bool Ogre::StringInterface::setParameter (const String & name, const String & value) virtual inherited
Generic parameter setting method.
Remarks
Call this method with the name of a parameter and a string version of the value to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
name The name of the parameter to set
value String value. Must be in the right format for the type specified in the parameter definition. See the StringConverter class for more information.
Returns
true if set was successful, false otherwise (NB no exceptions thrown - tolerant method)
Referenced by Ogre::StringInterface::copyParametersTo().
virtual void Ogre::StringInterface::setParameterList (const NameValuePairList & paramList) virtual inherited
Generic multiple parameter setting method.
Remarks
Call this method with a list of name / value pairs to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
paramList Name/value pair list
void Ogre::Font::setSource (const String & source)
Sets the source of the font.
Remarks
If you have created a font of type FT_IMAGE, this method tells the Font which image to use as the source for the characters. So the parameter should be the name of an appropriate image file. Note that when using an image as a font source, you will also need to tell the font where each character is located using setGlyphTexCoords (for each character).
If you have created a font of type FT_TRUETYPE, this method tells the Font which .ttf file to use to generate the text. You will also need to call setTrueTypeSize and setTrueTypeResolution, and call addCodePointRange as many times as required to define the range of glyphs you want to be available.
Parameters
source An image file or a truetype font, depending on the type of this font
virtual void Ogre::Resource::setToLoaded (void) inline virtual inherited
Change the Resource loading state to loaded.
References Ogre::AtomicScalar< T >::set().
void Ogre::Font::setTrueTypeResolution (uint ttfResolution)
Gets the resolution (dpi) of the font used to generate the texture (only required for FT_TRUETYPE).
Parameters
ttfResolution The resolution in dpi
void Ogre::Font::setTrueTypeSize (Real ttfSize)
Sets the size of a truetype font (only required for FT_TRUETYPE).
Parameters
ttfSize The size of the font in points. Note that the size of the font does not affect how big it is on the screen, just how large it is in the texture and thus how detailed it is.
void Ogre::Font::setType (FontType ftype)
Sets the type of font.
Must be set before loading.
virtual void Ogre::Resource::touch (void) virtual inherited
'Touches' the resource to indicate it has been used.
Reimplemented in Ogre::Material, and Ogre::UnifiedHighLevelGpuProgram.
Referenced by Ogre::Material::touch().
virtual void Ogre::Resource::unload (void) virtual inherited
Unloads the resource; this is not permanent, the resource can be reloaded later if required.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::Font::unloadImpl () protected virtual
Internal implementation of the 'unload' action; called regardless of whether this resource is being loaded from a ManualResourceLoader.
Implements Ogre::Resource.
virtual void Ogre::Resource::unprepareImpl (void) inline protected virtual inherited
Internal function for undoing the 'prepare' action.
Called when the load is completed, and when resources are unloaded when they are prepared but not yet loaded.
Reimplemented in Ogre::Mesh, Ogre::D3D11Texture, Ogre::D3D9Texture, Ogre::Material, Ogre::GL3PlusTexture, and Ogre::GLTexture.
Member Data Documentation
bool Ogre::Font::mAntialiasColour protected
For TRUE_TYPE font only.
uint Ogre::Font::mCharacterSpacer protected
Add a gap between letters vertically and horizonally prevents nasty artifacts caused by fonts atypically wide or tall characters.
CodePointMap Ogre::Font::mCodePointMap protected
CodePointRangeList Ogre::Font::mCodePointRangeList protected
Range of code points to generate glyphs for (truetype only)
ResourceManager* Ogre::Resource::mCreator protected inherited
Creator.
String Ogre::Resource::mGroup protected inherited
The name of the resource group.
ResourceHandle Ogre::Resource::mHandle protected inherited
Numeric handle for more efficient look up than name.
volatile bool Ogre::Resource::mIsBackgroundLoaded protected inherited
Is this resource going to be background loaded? Only applicable for multithreaded.
bool Ogre::Resource::mIsManual protected inherited
Is this file manually loaded?
ListenerList Ogre::Resource::mListenerList protected inherited
ManualResourceLoader* Ogre::Resource::mLoader protected inherited
Optional manual loader; if provided, data is loaded from here instead of a file.
AtomicScalar<LoadingState> Ogre::Resource::mLoadingState protected inherited
Is the resource currently loaded?
MaterialPtr Ogre::Font::mMaterial protected
The material which is generated for this font.
String Ogre::Resource::mName protected inherited
Unique name of the resource.
String Ogre::Resource::mOrigin protected inherited
Origin of this resource (e.g. script name) - optional.
CmdCharSpacer Ogre::Font::msCharacterSpacerCmd static protected
CmdCodePoints Ogre::Font::msCodePointsCmd static protected
size_t Ogre::Resource::mSize protected inherited
The size of the resource in bytes.
String Ogre::Font::mSource protected
Source of the font (either an image name or a truetype font)
CmdResolution Ogre::Font::msResolutionCmd static protected
CmdSize Ogre::Font::msSizeCmd static protected
CmdSource Ogre::Font::msSourceCmd static protected
size_t Ogre::Resource::mStateCount protected inherited
State count, the number of times this resource has changed state.
CmdType Ogre::Font::msTypeCmd static protected
TexturePtr Ogre::Font::mTexture protected
Texture pointer.
int Ogre::Font::mTtfMaxBearingY protected
Max distance to baseline of this (truetype) font.
uint Ogre::Font::mTtfResolution protected
Resolution (dpi) of truetype font.
Real Ogre::Font::mTtfSize protected
Size of the truetype font, in points.
FontType Ogre::Font::mType protected
The type of font.
Ogre::Resource::OGRE_AUTO_MUTEX inherited
The documentation for this class was generated from the following file:
OgreFont.h